# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `flipper-active_record` gem.
# Please instead update this file by running `bin/tapioca gem flipper-active_record`.


# source://flipper-active_record//lib/flipper/adapters/active_record.rb#6
module Flipper; end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#7
module Flipper::Adapters; end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#8
class Flipper::Adapters::ActiveRecord
  include ::Flipper::Adapter
  extend ::Flipper::Adapter::ClassMethods

  # Public: Initialize a new ActiveRecord adapter instance.
  #
  # name - The Symbol name for this adapter. Optional (default :active_record)
  # feature_class - The AR class responsible for the features table.
  # gate_class - The AR class responsible for the gates table.
  #
  # Allowing the overriding of name is so you can differentiate multiple
  # instances of this adapter from each other, if, for some reason, that is
  # a thing you do.
  #
  # Allowing the overriding of the default feature/gate classes means you
  # can roll your own tables and what not, if you so desire.
  #
  # @return [ActiveRecord] a new instance of ActiveRecord
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#59
  def initialize(options = T.unsafe(nil)); end

  # Public: Adds a feature to the set of known features.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#71
  def add(feature); end

  # Public: Clears the gate values for a feature.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#101
  def clear(feature); end

  # Public: Disables a gate for a given thing.
  #
  # feature - The Flipper::Feature for the gate.
  # gate - The Flipper::Gate to disable.
  # thing - The Flipper::Type being disabled for the gate.
  #
  # Returns true.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#189
  def disable(feature, gate, thing); end

  # Public: Enables a gate for a given thing.
  #
  # feature - The Flipper::Feature for the gate.
  # gate - The Flipper::Gate to enable.
  # thing - The Flipper::Type being enabled for the gate.
  #
  # Returns true.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#165
  def enable(feature, gate, thing); end

  # Public: The set of known features.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#66
  def features; end

  # Public: Gets the values for all gates for a given feature.
  #
  # Returns a Hash of Flipper::Gate#key => value.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#109
  def get(feature); end

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#131
  def get_all; end

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#114
  def get_multi(features); end

  # Public: Removes a feature from the set of known features.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#90
  def remove(feature); end

  # Private
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#209
  def unsupported_data_type(data_type); end

  private

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#241
  def delete(feature, gate); end

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#245
  def enable_multi(feature, gate, thing); end

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#263
  def result_for_gates(feature, gates); end

  # @raise [VALUE_TO_TEXT_WARNING]
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#215
  def set(feature, gate, thing, options = T.unsafe(nil)); end

  # Check if value column is text instead of string
  # See https://github.com/flippercloud/flipper/pull/692
  #
  # @return [Boolean]
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#288
  def value_not_text?; end

  # @return [Boolean]
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#302
  def warned_about_value_not_text?; end

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#297
  def with_connection(model = T.unsafe(nil), &block); end
end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#17
class Flipper::Adapters::ActiveRecord::Feature < ::Flipper::Adapters::ActiveRecord::Model
  include ::Flipper::Adapters::ActiveRecord::Feature::GeneratedAttributeMethods
  include ::Flipper::Adapters::ActiveRecord::Feature::GeneratedAssociationMethods

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#24
  def autosave_associated_records_for_gates(*args); end

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#24
  def validate_associated_records_for_gates(*args); end
end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#17
module Flipper::Adapters::ActiveRecord::Feature::GeneratedAssociationMethods
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#24
  def gate_ids; end

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#24
  def gate_ids=(ids); end

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#24
  def gates; end

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#24
  def gates=(value); end
end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#17
module Flipper::Adapters::ActiveRecord::Feature::GeneratedAttributeMethods; end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#30
class Flipper::Adapters::ActiveRecord::Gate < ::Flipper::Adapters::ActiveRecord::Model
  include ::Flipper::Adapters::ActiveRecord::Gate::GeneratedAttributeMethods
  include ::Flipper::Adapters::ActiveRecord::Gate::GeneratedAssociationMethods
end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#30
module Flipper::Adapters::ActiveRecord::Gate::GeneratedAssociationMethods; end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#30
module Flipper::Adapters::ActiveRecord::Gate::GeneratedAttributeMethods; end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#12
class Flipper::Adapters::ActiveRecord::Model < ::ActiveRecord::Base
  include ::Flipper::Adapters::ActiveRecord::Model::GeneratedAttributeMethods
  include ::Flipper::Adapters::ActiveRecord::Model::GeneratedAssociationMethods
end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#12
module Flipper::Adapters::ActiveRecord::Model::GeneratedAssociationMethods; end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#12
module Flipper::Adapters::ActiveRecord::Model::GeneratedAttributeMethods; end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#42
Flipper::Adapters::ActiveRecord::VALUE_TO_TEXT_WARNING = T.let(T.unsafe(nil), String)
