# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `phony_rails` gem.
# Please instead update this file by running `bin/tapioca gem phony_rails`.

# source://phony_rails//lib/validators/phony_validator.rb#60
module ActiveModel
  class << self
    # source://activemodel/7.0.4.2/lib/active_model.rb#71
    def eager_load!; end

    # source://activemodel/7.0.4.2/lib/active_model/gem_version.rb#5
    def gem_version; end

    # source://activemodel/7.0.4.2/lib/active_model/version.rb#7
    def version; end
  end
end

# source://phony_rails//lib/validators/phony_validator.rb#61
module ActiveModel::Validations
  include GeneratedInstanceMethods
  include ::ActiveSupport::Callbacks
  include ::ActiveModel::Validations::HelperMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveModel::Validations::ClassMethods
  mixes_in_class_methods ::ActiveModel::Callbacks
  mixes_in_class_methods ::ActiveSupport::Callbacks::ClassMethods
  mixes_in_class_methods ::ActiveSupport::DescendantsTracker
  mixes_in_class_methods ::ActiveModel::Translation
  mixes_in_class_methods ::ActiveModel::Validations::HelperMethods

  # source://activemodel/7.0.4.2/lib/active_model/validations.rb#301
  def errors; end

  # source://activemodel/7.0.4.2/lib/active_model/validations.rb#373
  def invalid?(context = T.unsafe(nil)); end

  def read_attribute_for_validation(*_arg0); end

  # source://activemodel/7.0.4.2/lib/active_model/validations.rb#334
  def valid?(context = T.unsafe(nil)); end

  # source://activemodel/7.0.4.2/lib/active_model/validations.rb#334
  def validate(context = T.unsafe(nil)); end

  # source://activemodel/7.0.4.2/lib/active_model/validations.rb#382
  def validate!(context = T.unsafe(nil)); end

  # source://activemodel/7.0.4.2/lib/active_model/validations/with.rb#137
  def validates_with(*args, &block); end

  private

  # source://activemodel/7.0.4.2/lib/active_model/validations.rb#283
  def initialize_dup(other); end

  # source://activemodel/7.0.4.2/lib/active_model/validations.rb#410
  def raise_validation_error; end

  # source://activemodel/7.0.4.2/lib/active_model/validations.rb#405
  def run_validations!; end

  module GeneratedClassMethods
    def __callbacks; end
    def __callbacks=(value); end
    def __callbacks?; end
    def _validators; end
    def _validators=(value); end
    def _validators?; end
  end

  module GeneratedInstanceMethods
    def __callbacks; end
    def __callbacks?; end
    def _validators; end
    def _validators?; end
  end
end

# source://phony_rails//lib/validators/phony_validator.rb#62
module ActiveModel::Validations::HelperMethods
  # source://activemodel/7.0.4.2/lib/active_model/validations/absence.rb#28
  def validates_absence_of(*attr_names); end

  # source://activemodel/7.0.4.2/lib/active_model/validations/acceptance.rb#108
  def validates_acceptance_of(*attr_names); end

  # source://activemodel/7.0.4.2/lib/active_model/validations/comparison.rb#77
  def validates_comparison_of(*attr_names); end

  # source://activemodel/7.0.4.2/lib/active_model/validations/confirmation.rb#75
  def validates_confirmation_of(*attr_names); end

  # source://activemodel/7.0.4.2/lib/active_model/validations/exclusion.rb#44
  def validates_exclusion_of(*attr_names); end

  # source://activemodel/7.0.4.2/lib/active_model/validations/format.rb#108
  def validates_format_of(*attr_names); end

  # source://activemodel/7.0.4.2/lib/active_model/validations/inclusion.rb#42
  def validates_inclusion_of(*attr_names); end

  # source://activemodel/7.0.4.2/lib/active_model/validations/length.rb#122
  def validates_length_of(*attr_names); end

  # source://activemodel/7.0.4.2/lib/active_model/validations/numericality.rb#205
  def validates_numericality_of(*attr_names); end

  # source://phony_rails//lib/validators/phony_validator.rb#63
  def validates_plausible_phone(*attr_names); end

  # source://activemodel/7.0.4.2/lib/active_model/validations/presence.rb#34
  def validates_presence_of(*attr_names); end

  # source://activemodel/7.0.4.2/lib/active_model/validations/length.rb#122
  def validates_size_of(*attr_names); end

  private

  # source://activemodel/7.0.4.2/lib/active_model/validations/helper_methods.rb#7
  def _merge_attributes(attr_names); end
end

class ActiveRecord::Base
  include ::ActiveModel::ForbiddenAttributesProtection
  include ::ActiveModel::AttributeAssignment
  include ::ActiveModel::Serialization
  include ::PhonyRails::Extension
  extend ::PhonyRails::Extension::ClassMethods
end

# source://phony_rails//lib/validators/phony_validator.rb#8
class PhonyPlausibleValidator < ::ActiveModel::EachValidator
  # Validates a String using Phony.plausible? method.
  #
  # source://phony_rails//lib/validators/phony_validator.rb#10
  def validate_each(record, attribute, value); end

  private

  # source://phony_rails//lib/validators/phony_validator.rb#39
  def country_code; end

  # source://phony_rails//lib/validators/phony_validator.rb#27
  def country_number; end

  # source://phony_rails//lib/validators/phony_validator.rb#35
  def country_number_from_country_code; end

  # source://phony_rails//lib/validators/phony_validator.rb#23
  def error_message; end

  # source://phony_rails//lib/validators/phony_validator.rb#47
  def normalized_country_code; end

  # source://phony_rails//lib/validators/phony_validator.rb#51
  def options_value(option); end

  # source://phony_rails//lib/validators/phony_validator.rb#43
  def record_country_code; end

  # source://phony_rails//lib/validators/phony_validator.rb#31
  def record_country_number; end
end

# source://phony_rails//lib/phony_rails/version.rb#3
module PhonyRails
  class << self
    # Returns the country dail code (eg. '31') for a number (eg. +31612341234).
    # Should probably be named 'country_number_from_number'.
    #
    # source://phony_rails//lib/phony_rails.rb#101
    def country_code_from_number(number); end

    # source://phony_rails//lib/phony_rails.rb#33
    def country_codes_hash; end

    # Returns the country (eg. 'NL') for a number (eg. +31612341234).
    #
    # source://phony_rails//lib/phony_rails.rb#108
    def country_from_number(number); end

    # source://phony_rails//lib/phony_rails.rb#27
    def country_number_for(country_code); end

    # source://phony_rails//lib/phony_rails.rb#10
    def default_country_code; end

    # source://phony_rails//lib/phony_rails.rb#14
    def default_country_code=(new_code); end

    # source://phony_rails//lib/phony_rails.rb#19
    def default_country_number; end

    # source://phony_rails//lib/phony_rails.rb#23
    def default_country_number=(new_number); end

    # source://phony_rails//lib/phony_rails.rb#90
    def extract_default_country_number(options = T.unsafe(nil), current_instance = T.unsafe(nil)); end

    # source://phony_rails//lib/phony_rails.rb#133
    def extract_extension(number_and_ext); end

    # source://phony_rails//lib/phony_rails.rb#140
    def format_extension(number, ext); end

    # This method requires a country_code attribute (eg. NL) and phone_number to be set.
    # Options:
    #   :country_number => The country dial code (eg. 31 for NL).
    #   :default_country_number => Fallback country code.
    #   :country_code => The country code we should use.
    #   :default_country_code => Some fallback code (eg. 'NL') that can be used as default (comes from phony_normalize_numbers method).
    #   :add_plus => Add a '+' in front so we know the country code is added. (default: true)
    #   :extension => Include the extension. (default: true)
    # This idea came from:
    #   http://www.redguava.com.au/2011/06/rails-convert-phone-numbers-to-international-format-for-sms/
    #
    # source://phony_rails//lib/phony_rails.rb#47
    def normalize_number(number, options = T.unsafe(nil), current_instance = T.unsafe(nil)); end

    # source://phony_rails//lib/phony_rails.rb#75
    def normalize_number_default_country(number, default_country_number); end

    # Wrapper for Phony.plausible?.  Takes the same options as #normalize_number.
    # NB: This method calls #normalize_number and passes _options_ directly to that method.
    # It uses the 'cc' option for Phony. This was a required param before?
    #
    # @return [Boolean]
    #
    # source://phony_rails//lib/phony_rails.rb#117
    def plausible_number?(number, options = T.unsafe(nil)); end
  end
end

# source://phony_rails//lib/phony_rails.rb#131
PhonyRails::COMMON_EXTENSIONS = T.let(T.unsafe(nil), Regexp)

# source://phony_rails//lib/phony_rails.rb#144
module PhonyRails::Extension
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::PhonyRails::Extension::ClassMethods

  # source://phony_rails//lib/phony_rails.rb#177
  def cache_original_attribute(current_instance, attribute); end
end

# source://phony_rails//lib/phony_rails.rb#184
module PhonyRails::Extension::ClassMethods
  # Use this method on the class level like:
  #   phony_normalize :phone_number, :fax_number, :default_country_code => 'NL'
  #
  # It checks your model object for a a country_code attribute (eg. 'NL') to do the normalizing so make sure
  # you've geocoded before calling this method!
  #
  # @raise [ArgumentError]
  #
  # source://phony_rails//lib/phony_rails.rb#202
  def phony_normalize(*attributes); end

  # Usage:
  #   phony_normalized_method :fax_number, :default_country_code => 'US'
  # Creates a normalized_fax_number method.
  #
  # source://phony_rails//lib/phony_rails.rb#220
  def phony_normalized_method(*attributes); end

  private

  # Creates a hash representing a conditional for before_validation
  # This allows conditional normalization
  # Returns something like `{ unless: -> { attribute == 'something' } }`
  # If no if/unless options passed in, returns `{ if: -> { true } }`
  #
  # source://phony_rails//lib/phony_rails.rb#243
  def create_before_validation_conditional_hash(options); end
end

# source://phony_rails//lib/phony_rails.rb#185
PhonyRails::Extension::ClassMethods::PHONY_RAILS_COLLECTION_VALID_KEYS = T.let(T.unsafe(nil), Array)

# source://phony_rails//lib/phony_rails/version.rb#4
PhonyRails::VERSION = T.let(T.unsafe(nil), String)

# source://phony_rails//lib/phony_rails/string_extensions.rb#3
class String
  include ::Comparable

  # Add a method to the String class so we can easily format phone numbers.
  # This enables:
  #   "31612341234".phony_formatted # => '06 12341234'
  #   "31612341234".phony_formatted(:spaces => '-') # => '06-12341234'
  # To first normalize a String use:
  #   "010-12341234".phony_formatted(:normalize => :NL)
  # To return nil when a number is not correct (checked using Phony.plausible?) use
  #   "010-12341234".phony_formatted(strict: true)
  # When an error occurs during conversion it will return the original String.
  # To raise an error use:
  #   "somestring".phone_formatted(raise: true)
  #
  # source://phony_rails//lib/phony_rails/string_extensions.rb#26
  def phony_formatted(options = T.unsafe(nil)); end

  # The bang method
  #
  # @raise [ArgumentError]
  #
  # source://phony_rails//lib/phony_rails/string_extensions.rb#44
  def phony_formatted!(options = T.unsafe(nil)); end

  # Usage:
  #   "+31 (0)30 1234 123".phony_normalized # => '+31301234123'
  #   "(0)30 1234 123".phony_normalized # => '301234123'
  #   "(0)30 1234 123".phony_normalized(country_code: 'NL') # => '301234123'
  #
  # @raise [ArgumentError]
  #
  # source://phony_rails//lib/phony_rails/string_extensions.rb#8
  def phony_normalized(options = T.unsafe(nil)); end
end
