# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sidekiq-pro` gem.
# Please instead update this file by running `bin/tapioca gem sidekiq-pro`.

# Implements Lua-based schedule enqueuer
#
# source://sidekiq-pro//lib/sidekiq/pro/version.rb#1
module Sidekiq
  class << self
    # source://sidekiq/7.2.1/lib/sidekiq.rb#134
    def configure_client; end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#122
    def configure_embed(&block); end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#96
    def configure_server(&block); end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#88
    def default_configuration; end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#84
    def default_job_options; end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#80
    def default_job_options=(hash); end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#56
    def dump_json(object); end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#64
    def ent?; end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#101
    def freeze!; end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#52
    def load_json(string); end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#92
    def logger; end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#60
    def pro?; end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#72
    def redis(&block); end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#68
    def redis_pool; end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#48
    def server?; end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#76
    def strict_args!(mode = T.unsafe(nil)); end

    # source://sidekiq/7.2.1/lib/sidekiq/transaction_aware_client.rb#33
    def transactional_push!; end

    # Allow targeting of Sidekiq API calls within a block
    # to a specific shard. Usage:
    #
    #   Sidekiq.via(SOME_POOL) do
    #     Sidekiq::Queue.all.sum(&:size)
    #   end
    #
    # source://sidekiq-pro//lib/sidekiq/pro/sharding.rb#8
    def via(pool); end

    # source://sidekiq/7.2.1/lib/sidekiq.rb#44
    def ❨╯°□°❩╯︵┻━┻; end
  end
end

# Provide a higher-level Batch abstraction for units of work.
# Given a set of work, we want to break the set down to individual jobs
# for Sidekiq to process in parallel but then have an overall
# notification when the entire set is complete.
#
#   batch = Sidekiq::Batch.new
#   batch.on(:complete, self.class, :to => current_user.email)
#   batch.jobs do
#     # push messages to sidekiq
#   end
#
# Sidekiq generates a unique Batch ID, along with the number of jobs pushed
# in the batch.
#
# Batches may be nested by creating a new Batch within another batch's +jobs+
# method.  When the child batch runs an event callback, it checks to see if
# it needs to fire the parent batch's event callback too.
#
# source://sidekiq-pro//lib/sidekiq/batch/callback.rb#4
class Sidekiq::Batch
  # @return [Batch] a new instance of Batch
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#73
  def initialize(bid = T.unsafe(nil)); end

  # Returns the value of attribute bid.
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#67
  def bid; end

  # Returns the value of attribute callback_queue.
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#71
  def callback_queue; end

  # Sets the attribute callback_queue
  #
  # @param value the value to set the attribute callback_queue to.
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#71
  def callback_queue=(_arg0); end

  # Returns the value of attribute callbacks.
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#68
  def callbacks; end

  # source://sidekiq-pro//lib/sidekiq/batch.rb#109
  def created_at; end

  # Returns the value of attribute description.
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#70
  def description; end

  # Sets the attribute description
  #
  # @param value the value to set the attribute description to.
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#70
  def description=(_arg0); end

  # source://sidekiq-pro//lib/sidekiq/batch.rb#113
  def expires_at; end

  # source://sidekiq-pro//lib/sidekiq/batch.rb#105
  def expiry; end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#124
  def include?(jid); end

  # source://sidekiq-pro//lib/sidekiq/batch.rb#131
  def invalidate_all; end

  # source://sidekiq-pro//lib/sidekiq/batch.rb#141
  def invalidate_jids(*jids); end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#151
  def invalidated?; end

  # Retrieve the current set of JIDs associated with this batch.
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#118
  def jids; end

  # Pass in a block which pushes all the work associated
  # with this batch to Sidekiq.
  #
  # Returns the set of JIDs added to the batch.
  #
  # Note: all jobs defined within the block are pushed to Redis atomically
  # so either the entire set of jobs are defined successfully or none at all.
  #
  # @raise [ArgumentError]
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#199
  def jobs(&block); end

  # set this per batch to override LINGER, e.g.
  #   batch = Sidekiq::Batch.new
  #   batch.linger = 600 # 10 minutes
  #   batch.jobs { ... }
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#63
  def linger; end

  # set this per batch to override LINGER, e.g.
  #   batch = Sidekiq::Batch.new
  #   batch.linger = 600 # 10 minutes
  #   batch.jobs { ... }
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#63
  def linger=(_arg0); end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#162
  def mutable?; end

  # Call a method upon completion or success of a batch.  You
  # may pass a bare Class, which will call "on_#{event}", or a
  # String with the exact 'Class#method' to call.
  #
  #   batch.on(:complete, MyClass)
  #   batch.on(:success, 'MyClass#foo')
  #   batch.on(:complete, MyClass, :email => current_user.email)
  #   batch.on(:death, MyClass, :email => current_user.email)
  #
  # The Class should implement a method signature like this:
  #
  #   def on_complete(status, options)
  #   end
  #
  # @raise [Immutable]
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#181
  def on(event, call, options = T.unsafe(nil)); end

  # source://sidekiq-pro//lib/sidekiq/batch.rb#101
  def parent; end

  # Returns the value of attribute parent_bid.
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#69
  def parent_bid; end

  # source://sidekiq-pro//lib/sidekiq/batch.rb#41
  def redis(bid, &block); end

  # Not a public API
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#286
  def register(jid); end

  # source://sidekiq-pro//lib/sidekiq/batch.rb#158
  def status; end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#124
  def valid?(jid); end

  private

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch.rb#299
  def immediate_registration?; end

  # source://sidekiq-pro//lib/sidekiq/batch.rb#303
  def increment_batch_jobs_to_redis(conn, jids); end

  class << self
    # source://sidekiq-pro//lib/sidekiq/batch.rb#37
    def redis(bid, &block); end
  end
end

# source://sidekiq-pro//lib/sidekiq/batch/callback.rb#5
class Sidekiq::Batch::Callback
  include ::Sidekiq::Job
  include ::Sidekiq::Job::Options
  extend ::Sidekiq::Job::Options::ClassMethods
  extend ::Sidekiq::Job::ClassMethods

  # source://sidekiq-pro//lib/sidekiq/batch/callback.rb#12
  def perform(event, bid, queue = T.unsafe(nil)); end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#137
  def sidekiq_options_hash; end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#149
  def sidekiq_options_hash=(_arg0); end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#137
  def sidekiq_retries_exhausted_block; end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#149
  def sidekiq_retries_exhausted_block=(_arg0); end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#137
  def sidekiq_retry_in_block; end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#149
  def sidekiq_retry_in_block=(_arg0); end

  private

  # source://sidekiq-pro//lib/sidekiq/batch/callback.rb#114
  def complete(status, queue); end

  # source://sidekiq-pro//lib/sidekiq/batch/callback.rb#21
  def constantize(str); end

  # source://sidekiq-pro//lib/sidekiq/batch/callback.rb#43
  def death(status, queue); end

  # source://sidekiq-pro//lib/sidekiq/batch/callback.rb#192
  def enqueue_callback(queue, args); end

  # source://sidekiq-pro//lib/sidekiq/batch/callback.rb#34
  def execute_callback(status, event, target, options); end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch/callback.rb#181
  def needs_complete?(bid); end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch/callback.rb#170
  def needs_success?(bid); end

  # source://sidekiq-pro//lib/sidekiq/batch/callback.rb#64
  def success(status, queue); end

  class << self
    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#104
    def sidekiq_options_hash; end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#112
    def sidekiq_options_hash=(val); end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#104
    def sidekiq_retries_exhausted_block; end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#112
    def sidekiq_retries_exhausted_block=(val); end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#104
    def sidekiq_retry_in_block; end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#112
    def sidekiq_retry_in_block=(val); end

    private

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#99
    def __synchronized_sidekiq_options_hash; end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#99
    def __synchronized_sidekiq_retries_exhausted_block; end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#99
    def __synchronized_sidekiq_retry_in_block; end
  end
end

# source://sidekiq-pro//lib/sidekiq/batch/callback.rb#9
Sidekiq::Batch::Callback::COMPLETE = T.let(T.unsafe(nil), String)

# source://sidekiq-pro//lib/sidekiq/batch/callback.rb#10
Sidekiq::Batch::Callback::DEATH = T.let(T.unsafe(nil), String)

# source://sidekiq-pro//lib/sidekiq/batch/callback.rb#8
Sidekiq::Batch::Callback::SUCCESS = T.let(T.unsafe(nil), String)

# source://sidekiq-pro//lib/sidekiq/batch/middleware.rb#7
class Sidekiq::Batch::Client
  include ::Sidekiq::ServerMiddleware

  # source://sidekiq-pro//lib/sidekiq/batch/middleware.rb#10
  def call(job_class, msg, queue, redis_pool); end
end

# source://sidekiq-pro//lib/sidekiq/batch/death.rb#33
class Sidekiq::Batch::DeadSet
  include ::Enumerable

  # source://sidekiq-pro//lib/sidekiq/batch/death.rb#42
  def each; end

  # source://sidekiq-pro//lib/sidekiq/batch/death.rb#36
  def size; end
end

# source://sidekiq-pro//lib/sidekiq/batch.rb#50
Sidekiq::Batch::EXPIRY = T.let(T.unsafe(nil), Integer)

# source://sidekiq-pro//lib/sidekiq/batch.rb#31
class Sidekiq::Batch::Empty
  include ::Sidekiq::Job
  include ::Sidekiq::Job::Options
  extend ::Sidekiq::Job::Options::ClassMethods
  extend ::Sidekiq::Job::ClassMethods

  # source://sidekiq-pro//lib/sidekiq/batch.rb#33
  def perform; end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#137
  def sidekiq_options_hash; end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#149
  def sidekiq_options_hash=(_arg0); end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#137
  def sidekiq_retries_exhausted_block; end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#149
  def sidekiq_retries_exhausted_block=(_arg0); end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#137
  def sidekiq_retry_in_block; end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#149
  def sidekiq_retry_in_block=(_arg0); end

  class << self
    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#104
    def sidekiq_options_hash; end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#112
    def sidekiq_options_hash=(val); end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#104
    def sidekiq_retries_exhausted_block; end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#112
    def sidekiq_retries_exhausted_block=(val); end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#104
    def sidekiq_retry_in_block; end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#112
    def sidekiq_retry_in_block=(val); end

    private

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#99
    def __synchronized_sidekiq_options_hash; end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#99
    def __synchronized_sidekiq_retries_exhausted_block; end

    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#99
    def __synchronized_sidekiq_retry_in_block; end
  end
end

# source://sidekiq-pro//lib/sidekiq/batch.rb#47
class Sidekiq::Batch::Immutable < ::RuntimeError; end

# Controls how long a batch record "lingers" in Redis before expiring.
# This allows APIs like Status#poll to check batch status even after
# the batch succeeds and is no longer needed.  You can lower this
# constant if you create lots of batches, want to reclaim the memory
# and don't use polling.
#
# source://sidekiq-pro//lib/sidekiq/batch.rb#57
Sidekiq::Batch::LINGER = T.let(T.unsafe(nil), Integer)

# source://sidekiq-pro//lib/sidekiq/batch.rb#45
class Sidekiq::Batch::NoSuchBatch < ::StandardError; end

# source://sidekiq-pro//lib/sidekiq/batch.rb#49
Sidekiq::Batch::ONE_DAY = T.let(T.unsafe(nil), Integer)

# source://sidekiq-pro//lib/sidekiq/batch/middleware.rb#23
class Sidekiq::Batch::Server
  include ::Sidekiq::ServerMiddleware

  # source://sidekiq-pro//lib/sidekiq/batch/middleware.rb#26
  def call(inst, job, queue); end

  private

  # source://sidekiq-pro//lib/sidekiq/batch/middleware.rb#123
  def add_failure(bid, job, queue, ex); end

  # source://sidekiq-pro//lib/sidekiq/batch/middleware.rb#64
  def add_success(bid, jid, queue); end

  # source://sidekiq-pro//lib/sidekiq/batch/middleware.rb#161
  def enqueue_callback(queue, args); end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch/middleware.rb#111
  def needs_callback?(bid, cb, term); end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch/middleware.rb#107
  def needs_complete?(bid); end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch/middleware.rb#103
  def needs_success?(bid); end
end

# A snapshot in time of the current Batch status.
#
# * total - number of jobs in this batch.
# * pending - number of jobs which have not reported success yet.
# * failures - number of jobs which have failed.
#
# Batch job(s) can fail and be retried through Sidekiq's retry feature.
# For this reason, a batch is considered complete once all jobs have
# been executed, even if one or more executions was a failure.
#
# source://sidekiq-pro//lib/sidekiq/batch/status.rb#15
class Sidekiq::Batch::Status
  # @return [Status] a new instance of Status
  #
  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#21
  def initialize(bid); end

  # Returns the value of attribute bid.
  #
  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#16
  def bid; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#71
  def callbacks; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#55
  def child_count; end

  # A Batch is considered complete when no jobs are pending or
  # the only pending jobs have already failed.  Any child batches
  # must have also completed.
  #
  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#162
  def complete?; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#75
  def complete_at; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#83
  def created_at; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#193
  def data; end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch/death.rb#14
  def dead?; end

  # Callers can scan the DeadSet for the given JIDs to
  # find the canonical copy of the job.
  #
  # source://sidekiq-pro//lib/sidekiq/batch/death.rb#22
  def dead_jids; end

  # source://sidekiq-pro//lib/sidekiq/batch/death.rb#28
  def death_at; end

  # Remove all info about this batch from Redis.  The main batch
  # data hash is kept around for 24 hours so it can be queried for status
  # after success.
  #
  # Returns the bid if anything was deleted, nil if nothing was deleted.
  #
  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#102
  def delete; end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#122
  def deleted?; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#67
  def description; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#92
  def expires_at; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#63
  def expiry; end

  # Batches store job failure info in a Hash, keyed off the bid.
  # The Hash contains { jid => [class name, error message] }
  #
  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#188
  def failure_info; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#154
  def failure_pct; end

  # Returns the value of attribute failures.
  #
  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#17
  def failures; end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#132
  def include?(jid); end

  # returns true if any or all jids in the batch have been invalidated.
  #
  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#139
  def invalidated?; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#126
  def jids; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#166
  def join; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#59
  def linger; end

  # @raise [NoSuchBatch]
  #
  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#26
  def load_data(bid); end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#49
  def parent; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#43
  def parent_batch; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#39
  def parent_bid; end

  # Returns the value of attribute pending.
  #
  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#18
  def pending; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#149
  def pending_pct; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#170
  def poll(polling_sleep = T.unsafe(nil)); end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#79
  def success_at; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#144
  def success_pct; end

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#210
  def to_json; end

  # Returns the value of attribute total.
  #
  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#19
  def total; end

  private

  # source://sidekiq-pro//lib/sidekiq/batch/status.rb#87
  def time_for(name); end
end

# source://sidekiq-pro//lib/sidekiq/batch/status.rb#184
class Sidekiq::Batch::Status::Failure < ::Struct
  # Returns the value of attribute backtrace
  #
  # @return [Object] the current value of backtrace
  def backtrace; end

  # Sets the attribute backtrace
  #
  # @param value [Object] the value to set the attribute backtrace to.
  # @return [Object] the newly set value
  def backtrace=(_); end

  # Returns the value of attribute error_class
  #
  # @return [Object] the current value of error_class
  def error_class; end

  # Sets the attribute error_class
  #
  # @param value [Object] the value to set the attribute error_class to.
  # @return [Object] the newly set value
  def error_class=(_); end

  # Returns the value of attribute error_message
  #
  # @return [Object] the current value of error_message
  def error_message; end

  # Sets the attribute error_message
  #
  # @param value [Object] the value to set the attribute error_message to.
  # @return [Object] the newly set value
  def error_message=(_); end

  # Returns the value of attribute jid
  #
  # @return [Object] the current value of jid
  def jid; end

  # Sets the attribute jid
  #
  # @param value [Object] the value to set the attribute jid to.
  # @return [Object] the newly set value
  def jid=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://sidekiq-pro//lib/sidekiq/batch.rb#65
Sidekiq::Batch::VALID_EVENTS = T.let(T.unsafe(nil), Array)

# source://sidekiq-pro//lib/sidekiq/batch/client.rb#4
module Sidekiq::BatchClient
  # The Sidekiq Batch client adds atomicity to batch definition:
  # all jobs created within the +jobs+ block are pushed into a
  # temporary array and then all flushed at once to Redis in a single
  # transaction.  This solves two problems:
  #
  # 1. We don't "half-create" a batch due to a networking issue
  # 2. We don't have a "completed" race condition when creating the jobs slower
  #    than we can process them.
  #
  # NB: creating very large numbers of jobs in one atomic block can be
  # dangerous -- it can spike Redis latency.  I generally recommend creating
  # blocks of jobs in parallel, 1,000 jobs per block, by creating an initial
  # set of jobs in the batch which reopen the batch and push those blocks.
  # It's not unusual for customers to have batches with 100,000+ jobs.
  #
  # source://sidekiq-pro//lib/sidekiq/batch/client.rb#21
  def flush(conn); end

  private

  # source://sidekiq-pro//lib/sidekiq/batch/client.rb#31
  def collected_payloads; end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/batch/client.rb#44
  def defining_batch?; end

  # source://sidekiq-pro//lib/sidekiq/batch/client.rb#35
  def raw_push(payloads); end
end

# Allows enumeration of all Batches in Redis.
# Example:
#
#   Sidekiq::BatchSet.new.each do |status|
#     puts status.bid
#   end
#
# source://sidekiq-pro//lib/sidekiq/pro/api.rb#14
class Sidekiq::BatchSet
  include ::Enumerable

  # source://sidekiq-pro//lib/sidekiq/pro/api.rb#23
  def each; end

  # source://sidekiq-pro//lib/sidekiq/pro/api.rb#17
  def size; end
end

# source://sidekiq-pro//lib/sidekiq/pro/push.rb#90
class Sidekiq::Client
  include ::Sidekiq::BatchClient

  # source://sidekiq/7.2.1/lib/sidekiq/client.rb#45
  def initialize(*args, **kwargs); end

  # source://sidekiq/7.2.1/lib/sidekiq/client.rb#23
  def middleware(&block); end

  # source://sidekiq/7.2.1/lib/sidekiq/client.rb#86
  def push(item); end

  # source://sidekiq/7.2.1/lib/sidekiq/client.rb#116
  def push_bulk(items); end

  # source://sidekiq/7.2.1/lib/sidekiq/client.rb#31
  def redis_pool; end

  # source://sidekiq/7.2.1/lib/sidekiq/client.rb#31
  def redis_pool=(_arg0); end

  private

  # source://sidekiq/7.2.1/lib/sidekiq/client.rb#248
  def atomic_push(conn, payloads); end

  # source://sidekiq-pro//lib/sidekiq/batch/client.rb#35
  def raw_push(payloads); end

  class << self
    # source://sidekiq/7.2.1/lib/sidekiq/client.rb#189
    def enqueue(klass, *args); end

    # source://sidekiq/7.2.1/lib/sidekiq/client.rb#217
    def enqueue_in(interval, klass, *args); end

    # source://sidekiq/7.2.1/lib/sidekiq/client.rb#196
    def enqueue_to(queue, klass, *args); end

    # source://sidekiq/7.2.1/lib/sidekiq/client.rb#203
    def enqueue_to_in(queue, interval, klass, *args); end

    # source://sidekiq/7.2.1/lib/sidekiq/client.rb#173
    def push(item); end

    # source://sidekiq/7.2.1/lib/sidekiq/client.rb#177
    def push_bulk(*_arg0, **_arg1, &_arg2); end

    # source://sidekiq-pro//lib/sidekiq/pro/push.rb#91
    def reliable_push!; end

    # source://sidekiq/7.2.1/lib/sidekiq/client.rb#163
    def via(pool); end
  end
end

# source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#36
module Sidekiq::Component
  # source://sidekiq/7.2.1/lib/sidekiq/component.rb#7
  def config; end

  # source://sidekiq/7.2.1/lib/sidekiq/component.rb#51
  def fire_event(event, options = T.unsafe(nil)); end

  # source://sidekiq/7.2.1/lib/sidekiq/component.rb#47
  def handle_exception(ex, ctx = T.unsafe(nil)); end

  # source://sidekiq/7.2.1/lib/sidekiq/component.rb#35
  def hostname; end

  # source://sidekiq/7.2.1/lib/sidekiq/component.rb#43
  def identity; end

  # source://sidekiq/7.2.1/lib/sidekiq/component.rb#23
  def logger; end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#37
  def metrics(&block); end

  # source://sidekiq/7.2.1/lib/sidekiq/component.rb#39
  def process_nonce; end

  # source://sidekiq/7.2.1/lib/sidekiq/component.rb#27
  def redis(&block); end

  # source://sidekiq/7.2.1/lib/sidekiq/component.rb#16
  def safe_thread(name, &block); end

  # source://sidekiq/7.2.1/lib/sidekiq/component.rb#31
  def tid; end

  # source://sidekiq/7.2.1/lib/sidekiq/component.rb#9
  def watchdog(last_words); end
end

# Enable various reliability add-ons:
#
#   Sidekiq.configure_server do |config|
#     config.super_fetch!
#     config.reliable_scheduler!
#     # enable both
#     config.reliable!
#   end
#
# source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#5
class Sidekiq::Config
  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#47
  def initialize(options = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def [](*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def []=(*args, **_arg1, &block); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#212
  def average_scheduled_poll_interval=(interval); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#111
  def capsule(name); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#56
  def capsules; end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#94
  def client_middleware; end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#68
  def concurrency; end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#64
  def concurrency=(val); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#203
  def death_handlers; end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#106
  def default_capsule(&block); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#6
  def dogstatsd=(thing); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#223
  def error_handlers; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def fetch(*args, **_arg1, &block); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#267
  def handle_exception(ex, ctx = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def has_key?(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def key?(*args, **_arg1, &block); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#241
  def logger; end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#252
  def logger=(logger); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#186
  def lookup(name, default_class = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def merge!(*args, **_arg1, &block); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#16
  def metrics(&block); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#136
  def new_redis_pool(size, name = T.unsafe(nil)); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#235
  def on(event, &block); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#90
  def queues; end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#86
  def queues=(val); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#158
  def redis; end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#122
  def redis=(hash); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#142
  def redis_info; end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#126
  def redis_pool; end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#181
  def register(name, instance); end

  # source://sidekiq-pro//lib/sidekiq-pro.rb#61
  def reliable!; end

  # source://sidekiq-pro//lib/sidekiq-pro.rb#56
  def reliable_scheduler!; end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#100
  def server_middleware; end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#6
  def statsd=(thing); end

  # source://sidekiq-pro//lib/sidekiq-pro.rb#35
  def super_fetch!(options = T.unsafe(nil), &block); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#58
  def to_json(*_arg0); end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#72
  def total_concurrency; end

  private

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#130
  def local_redis_pool; end

  # source://sidekiq/7.2.1/lib/sidekiq/config.rb#261
  def parameter_size(handler); end
end

# source://sidekiq-pro//lib/sidekiq/pro/job.rb#4
module Sidekiq::Job
  include ::Sidekiq::Job::Options

  mixes_in_class_methods ::Sidekiq::Job::Options::ClassMethods
  mixes_in_class_methods ::Sidekiq::Job::ClassMethods

  # source://sidekiq-pro//lib/sidekiq/pro/job.rb#7
  def batch; end

  # Returns the value of attribute bid.
  #
  # source://sidekiq-pro//lib/sidekiq/pro/job.rb#5
  def bid; end

  # Sets the attribute bid
  #
  # @param value the value to set the attribute bid to.
  #
  # source://sidekiq-pro//lib/sidekiq/pro/job.rb#5
  def bid=(_arg0); end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#156
  def jid; end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#156
  def jid=(_arg0); end

  # source://sidekiq/7.2.1/lib/sidekiq/job.rb#165
  def logger; end

  # Verify the job is still considered part of the batch.
  #
  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/pro/job.rb#12
  def valid_within_batch?; end

  class << self
    # source://sidekiq/7.2.1/lib/sidekiq/job.rb#158
    def included(base); end
  end
end

# source://sidekiq-pro//lib/sidekiq-pro.rb#14
Sidekiq::LICENSE = T.let(T.unsafe(nil), String)

# source://sidekiq-pro//lib/sidekiq-pro.rb#13
Sidekiq::NAME = T.let(T.unsafe(nil), String)

# source://sidekiq-pro//lib/sidekiq/pro/version.rb#2
module Sidekiq::Pro
  class << self
    # Track useful metrics within Sidekiq Pro and Sidekiq Enterprise.
    # Set to something that quacks like a ::Datadog::Statsd object from the dogstatsd-ruby gem.
    #
    # Datadog::Statsd is a big improvement over basic Statsd, it is recommended.
    # Configure it in your initializer like this:
    #
    #   Sidekiq::Pro.dogstatsd = ->{ ::Datadog::Statsd.new("metrics.acmecorp.com", 8125) }
    #
    # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#52
    def dogstatsd=(thing); end

    # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#56
    def metrics(&block); end
  end
end

# Allows for real-time configuration updates to be published to all
# Sidekiq processes cluster-wise.  For example, pausing and unpausing
# queues is now instantaneous via this mechanism.
#
# Event listeners register their interest via #register and must
# supply a `notify(verb, payload)` method.
#
#   Sidekiq::Pro::Config.register(self)
#
# You can broadcast a config event via `publish`:
#
#   Sidekiq::Pro::Config.publish(:boom, { 'some' => 'info' })
#
# The `notify` method on all registered listeners on all Sidekiq processes
# will be called.
#
# NOTE: pubsub is not persistent so you need to ensure that your listeners
# can pull the current state of the system from Redis.
#
# source://sidekiq-pro//lib/sidekiq/pro/config.rb#27
class Sidekiq::Pro::ConfigListener
  include ::Sidekiq::Component

  # @return [ConfigListener] a new instance of ConfigListener
  #
  # source://sidekiq-pro//lib/sidekiq/pro/config.rb#32
  def initialize(config); end

  # Takes a connection because it should be called as part of a larger
  # `multi` block to update Redis.
  #
  # source://sidekiq-pro//lib/sidekiq/pro/config.rb#45
  def publish(conn, verb, payload); end

  # source://sidekiq-pro//lib/sidekiq/pro/config.rb#39
  def register(handler); end

  # source://sidekiq-pro//lib/sidekiq/pro/config.rb#50
  def start; end

  # source://sidekiq-pro//lib/sidekiq/pro/config.rb#54
  def terminate(wait: T.unsafe(nil)); end

  private

  # NB: this method does not return
  #
  # source://sidekiq-pro//lib/sidekiq/pro/config.rb#63
  def event_loop(pubsub); end

  # source://sidekiq-pro//lib/sidekiq/pro/config.rb#74
  def listen; end
end

# source://sidekiq-pro//lib/sidekiq/pro/config.rb#30
Sidekiq::Pro::ConfigListener::CHANNEL = T.let(T.unsafe(nil), String)

# source://sidekiq-pro//lib/sidekiq/pro/version.rb#4
Sidekiq::Pro::MAJOR = T.let(T.unsafe(nil), Integer)

# source://sidekiq-pro//lib/sidekiq/pro/config.rb#5
class Sidekiq::Pro::Message < ::Struct
  # Returns the value of attribute payload
  #
  # @return [Object] the current value of payload
  def payload; end

  # Sets the attribute payload
  #
  # @param value [Object] the value to set the attribute payload to.
  # @return [Object] the newly set value
  def payload=(_); end

  # Returns the value of attribute verb
  #
  # @return [Object] the current value of verb
  def verb; end

  # Sets the attribute verb
  #
  # @param value [Object] the value to set the attribute verb to.
  # @return [Object] the newly set value
  def verb=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#60
module Sidekiq::Pro::Metrics; end

# Support for the improved Statsd API published by Datadog in the dogstatsd-ruby gem.
#
# source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#65
class Sidekiq::Pro::Metrics::Dogstatsd
  include ::Sidekiq::Component

  # @return [Dogstatsd] a new instance of Dogstatsd
  #
  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#68
  def initialize(config, statsd); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#116
  def batch(&block); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#96
  def count(name, value, opts = T.unsafe(nil)); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#88
  def decrement(name, opts = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#121
  def enabled?; end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#92
  def gauge(name, value, opts = T.unsafe(nil)); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#100
  def histogram(name, value, opts = T.unsafe(nil)); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#84
  def increment(name, opts = T.unsafe(nil)); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#80
  def location; end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#108
  def set(name, value, opts = T.unsafe(nil)); end

  # Returns the value of attribute statsd.
  #
  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#67
  def statsd; end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#112
  def time(name, opts = T.unsafe(nil), &block); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#104
  def timing(name, value, opts = T.unsafe(nil)); end
end

# Support for no metrics
#
# source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#128
class Sidekiq::Pro::Metrics::Nil
  include ::Sidekiq::Component

  # @return [Nil] a new instance of Nil
  #
  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#130
  def initialize(config); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#163
  def batch(&block); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#147
  def count(name, value, opts = T.unsafe(nil)); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#138
  def decrement(name, opts = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#134
  def enabled?; end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#144
  def gauge(name, value, opts = T.unsafe(nil)); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#153
  def histogram(name, value, opts = T.unsafe(nil)); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#141
  def increment(name, opts = T.unsafe(nil)); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#150
  def set(name, value, opts = T.unsafe(nil)); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#159
  def time(name, opts = T.unsafe(nil), &block); end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#156
  def timing(name, value, opts = T.unsafe(nil)); end
end

# source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#61
Sidekiq::Pro::Metrics::POOL_SIZE = T.let(T.unsafe(nil), Integer)

# source://sidekiq-pro//lib/sidekiq/pro/scripting.rb#3
module Sidekiq::Pro::Scripting
  class << self
    # source://sidekiq-pro//lib/sidekiq/pro/scripting.rb#124
    def bootstrap(component); end

    # source://sidekiq-pro//lib/sidekiq/pro/scripting.rb#134
    def call(conn = T.unsafe(nil), name, keys, args, component); end
  end
end

# source://sidekiq-pro//lib/sidekiq/pro/scripting.rb#4
Sidekiq::Pro::Scripting::LUA_SCRIPTS = T.let(T.unsafe(nil), Hash)

# source://sidekiq-pro//lib/sidekiq/pro/scripting.rb#122
Sidekiq::Pro::Scripting::SHAS = T.let(T.unsafe(nil), Hash)

# source://sidekiq-pro//lib/sidekiq/pro/version.rb#3
Sidekiq::Pro::VERSION = T.let(T.unsafe(nil), String)

# source://sidekiq-pro//lib/sidekiq/pro/api.rb#46
class Sidekiq::Queue
  # source://sidekiq/7.2.1/lib/sidekiq/api.rb#241
  def initialize(name = T.unsafe(nil)); end

  # source://sidekiq/7.2.1/lib/sidekiq/api.rb#324
  def as_json(options = T.unsafe(nil)); end

  # source://sidekiq/7.2.1/lib/sidekiq/api.rb#311
  def clear; end

  # Remove all jobs in the queue with the given class.
  # Accepts a String or Class but make sure to pass the fully
  # qualified Class name if you use a String.
  #
  # @raise [ArgumentError]
  #
  # source://sidekiq-pro//lib/sidekiq/pro/api.rb#69
  def delete_by_class(klass); end

  # Delete a job from the given queue.
  #
  # If the queue is being modified concurrently (e.g. another process is
  # pulling jobs from this queue), it is possible for the job to be "missed".
  # We iterate through the queue backwards to minimize this possibility.
  #
  # @raise [ArgumentError]
  #
  # source://sidekiq-pro//lib/sidekiq/pro/api.rb#52
  def delete_job(jid); end

  # source://sidekiq/7.2.1/lib/sidekiq/api.rb#275
  def each; end

  # source://sidekiq/7.2.1/lib/sidekiq/api.rb#305
  def find_job(jid); end

  # source://sidekiq/7.2.1/lib/sidekiq/api.rb#264
  def latency; end

  # source://sidekiq/7.2.1/lib/sidekiq/api.rb#238
  def name; end

  # source://sidekiq-pro//lib/sidekiq/pro/api.rb#114
  def pause!; end

  # @return [Boolean]
  #
  # source://sidekiq-pro//lib/sidekiq/pro/api.rb#130
  def paused?; end

  # source://sidekiq/7.2.1/lib/sidekiq/api.rb#250
  def size; end

  # source://sidekiq-pro//lib/sidekiq/pro/api.rb#100
  def unpause!; end

  # source://sidekiq/7.2.1/lib/sidekiq/api.rb#311
  def 💣; end

  class << self
    # source://sidekiq/7.2.1/lib/sidekiq/api.rb#234
    def all; end
  end
end

# Reliable push is designed to handle transient network failures,
# which cause the client to fail to deliver jobs to Redis.  It is not
# designed to be a perfectly reliable client but rather an incremental
# improvement over the existing client which will just fail in the face
# of any networking error.
#
# Each client process has a local queue, used for storage if a network problem
# is detected.  Jobs are pushed to that queue if normal delivery fails.  If
# normal delivery succeeds, the local queue is drained of any stored jobs.
#
# The standard `Sidekiq::Client.push` API returns a JID if the push to redis succeeded
# or raises an error if there was a problem.  With reliable push activated,
# no Redis networking errors will be raised.
#
# source://sidekiq-pro//lib/sidekiq/pro/push.rb#23
module Sidekiq::ReliableClient
  # source://sidekiq-pro//lib/sidekiq/pro/push.rb#55
  def drain; end

  # source://sidekiq-pro//lib/sidekiq/pro/push.rb#36
  def local_queue; end

  # source://sidekiq-pro//lib/sidekiq/pro/push.rb#40
  def raw_push(payloads); end

  # source://sidekiq-pro//lib/sidekiq/pro/push.rb#78
  def save_locally(pool, payloads, ex); end
end

# Raised if we try to save more than `backup_limit` client payloads.
#
# source://sidekiq-pro//lib/sidekiq/pro/push.rb#25
class Sidekiq::ReliableClient::BufferFull < ::RuntimeError; end

# Provide implicit `metrics` accessor inside server middleware
# and server components.
#
# source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#30
module Sidekiq::ServerMiddleware
  # source://sidekiq/7.2.1/lib/sidekiq/middleware/modules.rb#5
  def config; end

  # source://sidekiq/7.2.1/lib/sidekiq/middleware/modules.rb#5
  def config=(_arg0); end

  # source://sidekiq/7.2.1/lib/sidekiq/middleware/modules.rb#10
  def logger; end

  # source://sidekiq-pro//lib/sidekiq/pro/metrics.rb#31
  def metrics(&block); end

  # source://sidekiq/7.2.1/lib/sidekiq/middleware/modules.rb#14
  def redis(&block); end

  # source://sidekiq/7.2.1/lib/sidekiq/middleware/modules.rb#6
  def redis_pool; end
end
