# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sidekiq-ent` gem.
# Please instead update this file by running `bin/tapioca gem sidekiq-ent`.

# Parses cron expressions and computes the next occurence of the "job"
#
# source://sidekiq-ent//lib/sidekiq-ent/version.rb#1
module Sidekiq
  class << self
    # source://sidekiq/7.2.4/lib/sidekiq.rb#134
    def configure_client; end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#122
    def configure_embed(&block); end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#96
    def configure_server(&block); end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#88
    def default_configuration; end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#84
    def default_job_options; end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#80
    def default_job_options=(hash); end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#56
    def dump_json(object); end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#64
    def ent?; end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#101
    def freeze!; end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#52
    def load_json(string); end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#92
    def logger; end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#60
    def pro?; end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#72
    def redis(&block); end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#68
    def redis_pool; end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#48
    def server?; end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#76
    def strict_args!(mode = T.unsafe(nil)); end

    # source://sidekiq/7.2.4/lib/sidekiq/transaction_aware_client.rb#40
    def transactional_push!; end

    # source://sidekiq-pro/7.2.1/lib/sidekiq/pro/sharding.rb#8
    def via(pool); end

    # source://sidekiq/7.2.4/lib/sidekiq.rb#44
    def ❨╯°□°❩╯︵┻━┻; end
  end
end

# source://sidekiq-ent//lib/sidekiq-ent.rb#59
module Sidekiq::Component
  # source://sidekiq/7.2.4/lib/sidekiq/component.rb#7
  def config; end

  # source://sidekiq/7.2.4/lib/sidekiq/component.rb#51
  def fire_event(event, options = T.unsafe(nil)); end

  # source://sidekiq/7.2.4/lib/sidekiq/component.rb#47
  def handle_exception(ex, ctx = T.unsafe(nil)); end

  # source://sidekiq/7.2.4/lib/sidekiq/component.rb#35
  def hostname; end

  # source://sidekiq/7.2.4/lib/sidekiq/component.rb#43
  def identity; end

  # @return [Boolean]
  #
  # source://sidekiq-ent//lib/sidekiq-ent.rb#60
  def leader?; end

  # source://sidekiq/7.2.4/lib/sidekiq/component.rb#23
  def logger; end

  # source://sidekiq-pro/7.2.1/lib/sidekiq/pro/metrics.rb#37
  def metrics(&block); end

  # source://sidekiq/7.2.4/lib/sidekiq/component.rb#39
  def process_nonce; end

  # source://sidekiq/7.2.4/lib/sidekiq/component.rb#27
  def redis(&block); end

  # source://sidekiq/7.2.4/lib/sidekiq/component.rb#16
  def safe_thread(name, &block); end

  # source://sidekiq/7.2.4/lib/sidekiq/component.rb#31
  def tid; end

  # source://sidekiq/7.2.4/lib/sidekiq/component.rb#9
  def watchdog(last_words); end
end

# source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#5
class Sidekiq::Config
  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#47
  def initialize(options = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def [](*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def []=(*args, **_arg1, &block); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#212
  def average_scheduled_poll_interval=(interval); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#111
  def capsule(name); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#56
  def capsules; end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#94
  def client_middleware; end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#68
  def concurrency; end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#64
  def concurrency=(val); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#203
  def death_handlers; end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#106
  def default_capsule(&block); end

  # source://sidekiq-pro/7.2.1/lib/sidekiq/pro/metrics.rb#6
  def dogstatsd=(thing); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#223
  def error_handlers; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def fetch(*args, **_arg1, &block); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#267
  def handle_exception(ex, ctx = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def has_key?(*args, **_arg1, &block); end

  # Start a simple HTTP server which returns 200/OK and JSON data if the current
  # process is alive, used for Kubernetes health checks and similar.
  #
  # Examples:
  #   health_check(":7433") # binds to all interfaces, 0.0.0.0
  #   health_check("127.0.0.1:7433")
  #   health_check("[::1]:7433")
  #   health_check(7433) # binds to 127.0.0.1
  #
  # source://sidekiq-ent//lib/sidekiq-ent/liveness.rb#63
  def health_check(iface = T.unsafe(nil), &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def key?(*args, **_arg1, &block); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#241
  def logger; end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#252
  def logger=(logger); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#186
  def lookup(name, default_class = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def merge!(*args, **_arg1, &block); end

  # source://sidekiq-pro/7.2.1/lib/sidekiq/pro/metrics.rb#16
  def metrics(&block); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#136
  def new_redis_pool(size, name = T.unsafe(nil)); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#235
  def on(event, &block); end

  # A Loop generates jobs on some schedule, e.g. process new orders every 15 minutes.
  # Loops are registered on startup.
  #
  # Here's how to register a loop:
  #
  #   Sidekiq.configure_server do |config|
  #     config.periodic do |mgr|
  #       mgr.register "*/4 * * * * *", "ProcessOrders", retry: 3
  #     end
  #   end
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#18
  def periodic; end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#90
  def queues; end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#86
  def queues=(val); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#158
  def redis; end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#122
  def redis=(hash); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#142
  def redis_info; end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#126
  def redis_pool; end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#181
  def register(name, instance); end

  # source://sidekiq-pro/7.2.1/lib/sidekiq-pro.rb#61
  def reliable!; end

  # source://sidekiq-pro/7.2.1/lib/sidekiq-pro.rb#56
  def reliable_scheduler!; end

  # source://sidekiq-ent//lib/sidekiq-ent/metrics.rb#7
  def retain_history(interval = T.unsafe(nil), &block); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#100
  def server_middleware; end

  # source://sidekiq-pro/7.2.1/lib/sidekiq/pro/metrics.rb#6
  def statsd=(thing); end

  # source://sidekiq-pro/7.2.1/lib/sidekiq-pro.rb#35
  def super_fetch!(options = T.unsafe(nil), &block); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#58
  def to_json(*_arg0); end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#72
  def total_concurrency; end

  private

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#130
  def local_redis_pool; end

  # source://sidekiq/7.2.4/lib/sidekiq/config.rb#261
  def parameter_size(handler); end
end

# source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#33
class Sidekiq::CronParser
  # @return [CronParser] a new instance of CronParser
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#82
  def initialize(source, time_source = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#88
  def interpret_vixieisms(spec); end

  # returns the last occurence before the given date
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#137
  def last(now = T.unsafe(nil), num = T.unsafe(nil)); end

  # returns the next occurence after the given date
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#108
  def next(now = T.unsafe(nil), num = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#166
  def parse_element(elem, allowed_range); end

  protected

  # @return [Boolean]
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#244
  def date_valid?(t, dir = T.unsafe(nil)); end

  # returns the smallest element from allowed which is greater than current
  # returns nil if no matching value was found
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#304
  def find_best_next(current, allowed, dir); end

  # returns a list of days which do both match time_spec[:dom] or time_spec[:dow]
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#200
  def interpolate_weekdays(year, month); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#205
  def interpolate_weekdays_without_cache(year, month); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#248
  def nudge_date(t, dir = T.unsafe(nil), can_nudge_month = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#256
  def nudge_hour(t, dir = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#264
  def nudge_minute(t, dir = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#232
  def nudge_month(t, dir = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#228
  def nudge_year(t, dir = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#191
  def recursive_calculate(meth, time, num); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#292
  def stepped_range(rng, step = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#286
  def substitute_parse_symbols(str); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#272
  def time_specs; end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#312
  def validate_source; end
end

# internal "mutable" time representation
#
# source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#35
class Sidekiq::CronParser::InternalTime
  # @return [InternalTime] a new instance of InternalTime
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#39
  def initialize(time, time_source = T.unsafe(nil)); end

  # Returns the value of attribute day.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#36
  def day; end

  # Sets the attribute day
  #
  # @param value the value to set the attribute day to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#36
  def day=(_arg0); end

  # Returns the value of attribute hour.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#36
  def hour; end

  # Sets the attribute hour
  #
  # @param value the value to set the attribute hour to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#36
  def hour=(_arg0); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#54
  def inspect; end

  # Returns the value of attribute min.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#36
  def min; end

  # Sets the attribute min
  #
  # @param value the value to set the attribute min to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#36
  def min=(_arg0); end

  # Returns the value of attribute month.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#36
  def month; end

  # Sets the attribute month
  #
  # @param value the value to set the attribute month to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#36
  def month=(_arg0); end

  # Returns the value of attribute time_source.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#37
  def time_source; end

  # Sets the attribute time_source
  #
  # @param value the value to set the attribute time_source to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#37
  def time_source=(_arg0); end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#50
  def to_time; end

  # Returns the value of attribute year.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#36
  def year; end

  # Sets the attribute year
  #
  # @param value the value to set the attribute year to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#36
  def year=(_arg0); end
end

# source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#165
Sidekiq::CronParser::SUBELEMENT_REGEX = T.let(T.unsafe(nil), Regexp)

# source://sidekiq-ent//lib/sidekiq-ent/periodic/cron.rb#59
Sidekiq::CronParser::SYMBOLS = T.let(T.unsafe(nil), Hash)

# keep these names short to minimize overhead
#
# source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#7
class Sidekiq::Enc < ::Struct
  # Returns the value of attribute blob
  #
  # @return [Object] the current value of blob
  def blob; end

  # Sets the attribute blob
  #
  # @param value [Object] the value to set the attribute blob to.
  # @return [Object] the newly set value
  def blob=(_); end

  # Returns the value of attribute c
  #
  # @return [Object] the current value of c
  def c; end

  # Sets the attribute c
  #
  # @param value [Object] the value to set the attribute c to.
  # @return [Object] the newly set value
  def c=(_); end

  # Returns the value of attribute iv
  #
  # @return [Object] the current value of iv
  def iv; end

  # Sets the attribute iv
  #
  # @param value [Object] the value to set the attribute iv to.
  # @return [Object] the newly set value
  def iv=(_); end

  # Returns the value of attribute tag
  #
  # @return [Object] the current value of tag
  def tag; end

  # Sets the attribute tag
  #
  # @param value [Object] the value to set the attribute tag to.
  # @return [Object] the newly set value
  def tag=(_); end

  # Returns the value of attribute v
  #
  # @return [Object] the current value of v
  def v; end

  # Sets the attribute v
  #
  # @param value [Object] the value to set the attribute v to.
  # @return [Object] the newly set value
  def v=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://sidekiq-ent//lib/sidekiq-ent/version.rb#2
module Sidekiq::Enterprise
  class << self
    # source://sidekiq-ent//lib/sidekiq-ent/unique.rb#199
    def unique!; end
  end
end

# source://sidekiq-ent//lib/sidekiq-ent/census.rb#21
class Sidekiq::Enterprise::Census
  include ::Sidekiq::Component

  # @return [Census] a new instance of Census
  #
  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#24
  def initialize(config, settings = T.unsafe(nil), hostname = T.unsafe(nil), helpers = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#98
  def env; end

  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#131
  def fallback(p); end

  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#156
  def fetch_creds(settings, hostname); end

  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#102
  def minute; end

  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#121
  def network_call(uri); end

  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#141
  def parameterize; end

  # Leaders send their daily census report during the hour of 3AM Pacific
  #
  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#84
  def pause(hour = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#55
  def perform; end

  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#51
  def pwd; end

  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#106
  def scale_metrics; end

  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#34
  def start; end

  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#47
  def user; end

  # @return [Boolean]
  #
  # source://sidekiq-ent//lib/sidekiq-ent/census.rb#92
  def valid?; end
end

# This class can auto-{en,de}crypt a secret argument for
# sensitive payloads.  You enable the feature by
# initializing it:
#
#   Sidekiq::Enterprise::Crypto.enable(active_version: 1) do |version|
#     <return key>
#   end
#
# where the block must return the bytes of the symmetric key to use
# for encryption and decryption of the given version.  With key rotation,
# you bump the active_version and supply the new key for that new version.
#
# You can create a random key using OpenSSL and `irb`:
#
#   require 'openssl'
#   File.open("/tmp/my1.key", "w") { |file| file.write(OpenSSL::Cipher.new("aes-256-cbc").random_key) }
#
# and now tell Sidekiq about it:
#
#   Sidekiq::Enterprise::Crypto.enable(active_version: 1) do |version|
#     File.read("/tmp/my#{version}.key")
#   end
#
# If using Heroku, you can load the secret key into an ENV var and access that instead.
#
# Once you've set up the crypto subsystem, you can activate encryption for a
# given Job's arguments like so:
#
#     class MySecretJob
#       include Sidekiq::Job
#       sidekiq_options encrypt: true
#
# NOTES
# ----------
#
# * Encryption adds about 100 bytes to the size of arguments.  My MBP can perform about 70,000 enc/dec
#   round trips per second.
# * **ONLY** the last argument is encrypted.  Any error message and backtrace will still be plaintext within a job.
# * The unique jobs feature will not work on encrypted jobs, since all encrypted arguments are unique.
#
# source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#50
module Sidekiq::Enterprise::Crypto
  class << self
    # source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#51
    def enable(opts = T.unsafe(nil), &block); end
  end
end

# source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#136
class Sidekiq::Enterprise::Crypto::Client
  include ::Sidekiq::ServerMiddleware

  # source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#138
  def call(job_klass, job, queue, redis_pool); end

  # source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#163
  def encrypt(thing, scheme); end
end

# source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#69
class Sidekiq::Enterprise::Crypto::Default
  # @return [Default] a new instance of Default
  #
  # source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#72
  def initialize(opts = T.unsafe(nil), &block); end

  # Decrypts the blob of data, returning `thing`
  #
  # source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#116
  def decrypt(blob); end

  # Encrypts `thing`, returns a blob of binary data.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#100
  def encrypt(thing); end

  # source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#95
  def key_for(version); end
end

# source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#70
Sidekiq::Enterprise::Crypto::Default::KEYS = T.let(T.unsafe(nil), Hash)

# source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#134
Sidekiq::Enterprise::Crypto::NON_BASE64 = T.let(T.unsafe(nil), Regexp)

# source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#133
Sidekiq::Enterprise::Crypto::SCHEMES = T.let(T.unsafe(nil), Hash)

# source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#168
class Sidekiq::Enterprise::Crypto::Server
  include ::Sidekiq::ServerMiddleware

  # source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#170
  def call(inst, job, queue); end

  # source://sidekiq-ent//lib/sidekiq-ent/encryption.rb#184
  def decrypt(blob, scheme); end
end

# source://sidekiq-ent//lib/sidekiq-ent/metrics.rb#26
class Sidekiq::Enterprise::History
  include ::Sidekiq::Component

  # @return [History] a new instance of History
  #
  # source://sidekiq-ent//lib/sidekiq-ent/metrics.rb#31
  def initialize(config); end

  # source://sidekiq-ent//lib/sidekiq-ent/metrics.rb#58
  def capture; end

  # source://sidekiq-ent//lib/sidekiq-ent/metrics.rb#65
  def capture_default(stats); end

  # Returns the value of attribute custom.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/metrics.rb#29
  def custom; end

  # Sets the attribute custom
  #
  # @param value the value to set the attribute custom to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/metrics.rb#29
  def custom=(_arg0); end

  # Returns the value of attribute interval.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/metrics.rb#28
  def interval; end

  # Sets the attribute interval
  #
  # @param value the value to set the attribute interval to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/metrics.rb#28
  def interval=(_arg0); end

  # source://sidekiq-ent//lib/sidekiq-ent/metrics.rb#47
  def run; end

  # source://sidekiq-ent//lib/sidekiq-ent/metrics.rb#37
  def start; end

  # source://sidekiq-ent//lib/sidekiq-ent/metrics.rb#43
  def stop; end
end

# source://sidekiq-ent//lib/sidekiq-ent/liveness.rb#4
class Sidekiq::Enterprise::Liveness < ::Sidekiq::HttpServer
  include ::Sidekiq::Component

  # @return [Liveness] a new instance of Liveness
  # @yield [_self]
  # @yieldparam _self [Sidekiq::Enterprise::Liveness] the object that the method was called on
  #
  # source://sidekiq-ent//lib/sidekiq-ent/liveness.rb#7
  def initialize(iface, cfg = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/liveness.rb#28
  def ip_auth_handler(*_arg0); end

  # source://sidekiq-ent//lib/sidekiq-ent/liveness.rb#32
  def request_handler(req, res); end
end

# source://sidekiq-ent//lib/sidekiq-ent/version.rb#4
Sidekiq::Enterprise::MAJOR = T.let(T.unsafe(nil), Integer)

# source://sidekiq-ent//lib/sidekiq-ent/scripting.rb#3
module Sidekiq::Enterprise::Scripting
  class << self
    # source://sidekiq-ent//lib/sidekiq-ent/scripting.rb#7
    def bootstrap(config); end

    # source://sidekiq-ent//lib/sidekiq-ent/scripting.rb#17
    def call(name, keys, args, config); end
  end
end

# source://sidekiq-ent//lib/sidekiq-ent/scripting.rb#4
Sidekiq::Enterprise::Scripting::LUA = T.let(T.unsafe(nil), Hash)

# source://sidekiq-ent//lib/sidekiq-ent/scripting.rb#5
Sidekiq::Enterprise::Scripting::SHAS = T.let(T.unsafe(nil), Hash)

# The Unique middleware adds a check before the push of a Sidekiq
# job to Redis to see if the same job is already thought to be within Redis.
#
# This sets a tag in Redis which expires in N seconds. The same job cannot
# be enqueued while this tag exists.
#
# When `perform` returns successfully we clear the tag so another identical
# job can be enqueued at that point.  A raised error does **not** clear out
# the tag so the same job cannot be pushed while the errored job is pending retry.
#
# If you are scheduling a unique job to run in the future, the uniqueness
# will last until after the job is scheduled to run:
#
#     class MyUniqueJob
#       include Sidekiq::Job
#       sidekiq_options unique_for: 5 minutes
#     end
#     MyUniqueJob.perform_in(1.hour, 1, 2, 3)
#
# Other duplicate jobs will be ignored for 65 minutes or until the job runs
# successfully (in 60 minutes).
#
# You can "force push" a job to Redis by overriding `unique_for` to false:
#
#     MyUniqueJob.set(unique_for: false).perform_async(1,2,3)
#
# There are several caveats with this feature and ways in which it can fail.
# Do not depend on it for guaranteed uniqueness but rather as a way to prune
# redundant jobs.  Your jobs should still be idempotent.
#
# Caveats:
#
# 1. Only works with simple parameters, no symbols, objects, etc, as the parameters
#    must go thru the JSON serialization round trip without modification.
# 2. If the job raises an error and does not retry, the tag will remain in Redis
#    until it expires.  If you don't want jobs to retry, you should also set their
#    uniqueness period very short.
#
# Usage:
#
# In your initializer:
#
#     Sidekiq::Enterprise.unique! unless Rails.env.test?
#
# In your job:
#
#     sidekiq_options unique_for: 20.minutes
#
# source://sidekiq-ent//lib/sidekiq-ent/unique.rb#56
module Sidekiq::Enterprise::Unique
  class << self
    # If you wish to control the elements which Sidekiq Enterprise
    # uses to calculate the lock, you can implement `sidekiq_unique_context`
    # as a class method on your job. This method should return the Array of
    # elements. See above for the default implementation which handles both
    # Sidekiq::Job and ActiveJob::Base.
    #
    # source://sidekiq-ent//lib/sidekiq-ent/unique.rb#99
    def context_for(_, job); end

    # Special case AJ's wrapper class so unique locks can work
    # with AJ's special argument handling.
    #
    # source://sidekiq-ent//lib/sidekiq-ent/unique.rb#84
    def default_context_for(_, job); end

    # Check to see if the unique lock is currently present
    # for the given (queue, klass, args) tuple.  Keep in mind that
    # the args must be *exactly* what would be deserialized
    # from JSON so no symbols, objects or non-JSON datatypes.
    #
    # Note this method IS RACY.  It can return false and then another
    # thread take the lock microseconds later - treat it as advisory only.
    #
    # Returns truthy if the unique lock is present.
    #
    # @return [Boolean]
    #
    # source://sidekiq-ent//lib/sidekiq-ent/unique.rb#72
    def locked?(queue = T.unsafe(nil), klass, args); end

    # source://sidekiq-ent//lib/sidekiq-ent/unique.rb#167
    def unlock(job, cfg = T.unsafe(nil)); end
  end
end

# source://sidekiq-ent//lib/sidekiq-ent/unique.rb#123
class Sidekiq::Enterprise::Unique::Client
  include ::Sidekiq::ServerMiddleware

  # source://sidekiq-ent//lib/sidekiq-ent/unique.rb#125
  def call(inst, job, queue, redis_pool); end
end

# source://sidekiq-ent//lib/sidekiq-ent/unique.rb#59
Sidekiq::Enterprise::Unique::LOCKED_KEY = T.let(T.unsafe(nil), String)

# source://sidekiq-ent//lib/sidekiq-ent/unique.rb#177
class Sidekiq::Enterprise::Unique::Server
  include ::Sidekiq::ServerMiddleware

  # source://sidekiq-ent//lib/sidekiq-ent/unique.rb#179
  def call(inst, job, queue); end
end

# source://sidekiq-ent//lib/sidekiq-ent/unique.rb#60
Sidekiq::Enterprise::Unique::TOKEN_KEY = T.let(T.unsafe(nil), String)

# source://sidekiq-ent//lib/sidekiq-ent/unique.rb#57
Sidekiq::Enterprise::Unique::UNIQUE_KEY = T.let(T.unsafe(nil), String)

# source://sidekiq-ent//lib/sidekiq-ent/unique.rb#58
Sidekiq::Enterprise::Unique::UNIQUE_UNTIL = T.let(T.unsafe(nil), String)

# source://sidekiq-ent//lib/sidekiq-ent/version.rb#3
Sidekiq::Enterprise::VERSION = T.let(T.unsafe(nil), String)

# Implements a simple HTTP-server by using John W. Small's (jsmall@laser.net)
# ruby-generic-server: GServer.
#
# source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#11
class Sidekiq::HttpServer < ::GServer
  # +handle_obj+ specifies the object, that receives calls from +request_handler+
  # and +ip_auth_handler+
  #
  # @return [HttpServer] a new instance of HttpServer
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#15
  def initialize(handle_obj, port = T.unsafe(nil), host = T.unsafe(nil), maxConnections = T.unsafe(nil), stdlog = T.unsafe(nil), audit = T.unsafe(nil), debug = T.unsafe(nil)); end

  private

  # Returns a string which represents the time as rfc1123-date of HTTP-date
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#112
  def http_date(aTime); end

  # Generates a Hash with the HTTP headers
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#101
  def http_header(header = T.unsafe(nil)); end

  # Returns a string which includes the status code message as,
  # http headers, and body for the response.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#118
  def http_resp(status_code, status_message = T.unsafe(nil), header = T.unsafe(nil), body = T.unsafe(nil)); end

  # Handles the HTTP request and writes the response back to the client, +io+.
  #
  # If an Exception is raised while handling the request, the client will receive
  # a 500 "Internal Server Error" message.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#133
  def serve(io); end
end

# source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#23
Sidekiq::HttpServer::CRLF = T.let(T.unsafe(nil), String)

# Default header for the server name
#
# source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#28
Sidekiq::HttpServer::DEFAULT_HEADER = T.let(T.unsafe(nil), Hash)

# source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#24
Sidekiq::HttpServer::HTTP_PROTO = T.let(T.unsafe(nil), String)

# source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#42
class Sidekiq::HttpServer::Request
  # @return [Request] a new instance of Request
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#45
  def initialize(data, method = T.unsafe(nil), path = T.unsafe(nil), proto = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#50
  def content_length; end

  # Returns the value of attribute data.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#43
  def data; end

  # Returns the value of attribute header.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#43
  def header; end

  # Returns the value of attribute method.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#43
  def method; end

  # Returns the value of attribute path.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#43
  def path; end

  # Returns the value of attribute proto.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#43
  def proto; end
end

# source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#57
class Sidekiq::HttpServer::Response
  # @return [Response] a new instance of Response
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#61
  def initialize(status = T.unsafe(nil)); end

  # Returns the value of attribute body.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#59
  def body; end

  # Sets the attribute body
  #
  # @param value the value to set the attribute body to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#59
  def body=(_arg0); end

  # Returns the value of attribute header.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#58
  def header; end

  # Returns the value of attribute status.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#59
  def status; end

  # Sets the attribute status
  #
  # @param value the value to set the attribute status to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#59
  def status=(_arg0); end

  # Returns the value of attribute status_message.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#59
  def status_message; end

  # Sets the attribute status_message
  #
  # @param value the value to set the attribute status_message to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#59
  def status_message=(_arg0); end
end

# source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#25
Sidekiq::HttpServer::SERVER_NAME = T.let(T.unsafe(nil), String)

# Mapping of status codes and error messages
#
# source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#33
Sidekiq::HttpServer::StatusCodeMapping = T.let(T.unsafe(nil), Hash)

# A case-insensitive Hash class for HTTP header
#
# source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#69
class Sidekiq::HttpServer::Table
  include ::Enumerable

  # @return [Table] a new instance of Table
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#72
  def initialize(hash = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#77
  def [](key); end

  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#81
  def []=(key, value); end

  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#90
  def each; end

  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#85
  def update(hash); end

  # Output the Hash table for the HTTP header
  #
  # source://sidekiq-ent//lib/sidekiq-ent/hserver.rb#95
  def writeTo(port); end
end

# source://sidekiq-ent//lib/sidekiq-ent.rb#23
Sidekiq::LICENSE = T.let(T.unsafe(nil), String)

# source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#41
module Sidekiq::Limiter
  class << self
    # Returns the value of attribute backoff.
    #
    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#153
    def backoff; end

    # Sets the attribute backoff
    #
    # @param value the value to set the attribute backoff to.
    #
    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#153
    def backoff=(_arg0); end

    # Register a bucket-based rate limiter within Redis.  Buckets can be
    # per :second, :minute, :hour or :day.
    #
    # Limit Stripe operations to 10 per second:
    #
    #     Sidekiq::Limiter.bucket(:stripe, 10, :second)
    #
    # Bucket means that you can perform 10 operations at 12:44:03.999 and
    # then another 10 operations at 12:44:04.000, because each interval is
    # considered a bucket.
    #
    # Options:
    #   :ttl - time for the data to live in Redis, default 90 days
    #   :wait_timeout - seconds to wait for the rate limit or raises a
    #     Sidekiq::Limiter::OverLimit, 0 means never wait, default 5
    #   :policy - what should the API do if rate limit cannot be met, legal values: [:raise, :skip],
    #     :raise will raise Sidekiq::Limiter::OverLimit, :skip will return without executing the block,
    #     defaults to :raise
    #   :backoff - a Proc(limiter, job, ex) which calculates an integer number of seconds to pause before retrying in case of OverLimit
    #
    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#205
    def bucket(name, count, interval, options = T.unsafe(nil)); end

    # Register a concurrent rate limiter within Redis.
    #
    # Limit to 50 concurrent ERP operations:
    #
    #     Sidekiq::Limiter.concurrent(:erp, 50, wait_timeout: 10)
    #
    # Options:
    #   :ttl - time for the data to live in Redis, default 90 days
    #   :lock_timeout - seconds before a concurrent lock is automatically released, necessary if a
    #     process crashes while holding a lock, default 30.  **Your concurrent operations
    #     must take less than this amount of time!**
    #   :wait_timeout - seconds to wait for the rate limit or raises a
    #     Sidekiq::Limiter::OverLimit, 0 means never wait, default 5
    #   :policy - what should the API do if rate limit cannot be met, legal values: [:raise, :skip],
    #     :raise will raise Sidekiq::Limiter::OverLimit, :skip will return without executing the block,
    #     defaults to :raise
    #   :backoff - a Proc(limiter, job, ex) which calculates an integer number of seconds to pause before retrying in case of OverLimit
    #
    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#176
    def concurrent(name, count, options = T.unsafe(nil)); end

    # Globally configure the Limiter subsystem:
    #
    # Sidekiq::Limiter.configure do |config|
    #   config.redis = { url: 'redis://localhost/0' }
    #   config.errors << Foo::Bar
    #   config.backoff = ->(limiter, job, ex) do
    #     10
    #   end
    # end
    #
    # @yield [_self]
    # @yieldparam _self [Sidekiq::Limiter] the object that the method was called on
    #
    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#84
    def configure; end

    # Returns the value of attribute errors.
    #
    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#137
    def errors; end

    # Sets the attribute errors
    #
    # @param value the value to set the attribute errors to.
    #
    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#137
    def errors=(_arg0); end

    # Register a "leaky bucket"-based rate limiter within Redis.
    # You define it to allow X operations per Y seconds.
    #
    # The leaky bucket allows the caller to perform X operations immediately
    # but then the bucket slowly leaks, emptying over Y seconds.
    #
    # Limit Shopify operations to 20 every 5 seconds:
    #
    #     Sidekiq::Limiter.leaky(:shopify, 20, 5)
    #
    # One important note:
    #
    #     Sidekiq::Limiter.leaky(:shopify, 4, :second)
    #     Sidekiq::Limiter.leaky(:shopify, 240, :minute)
    #
    # These are the same ratios (240 / 60) vs (20 / 5) vs (4 / 1) with one important
    # caveat: the numerator is the burst allowance. The user can only
    # burst 4 operations before throttling, whereas the previous allows
    # 20 operations before throttling. The last one allows 240 simultaneous
    # operations before throttling, it's up to you to determine how much burst leeway
    # you want to give to your users. Once full, they all drain at the same rate.
    #
    # Options:
    #   :ttl - time for the data to live in Redis, default 24 hours
    #   :wait_timeout - seconds to wait for the rate limit or raises a
    #     Sidekiq::Limiter::OverLimit, 0 means never wait, default 5
    #   :policy - what should the API do if rate limit cannot be met, legal values: [:raise, :skip],
    #     :raise will raise Sidekiq::Limiter::OverLimit, :skip will return without executing the block,
    #     defaults to :raise
    #   :backoff - a Proc(limiter, job, ex) which calculates an integer number of seconds to pause before retrying in case of OverLimit
    #
    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#244
    def leaky(name, count, interval, options = T.unsafe(nil)); end

    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#122
    def logger; end

    # Register a points-based leaky bucket rate limiter within Redis.
    # This type of limiter is frequently used with GraphQL APIs from
    # companies like Shopify or GitHub. For example: you get 10,000 points per
    # minute. An arbitrary GraphQL query might use 300 or 1000 points.
    # You need to provide an estimate for the number of points which will be consumed by
    # your operation and the rate limiter will ensure your call has at least that many points
    # left.
    #
    # For Shopify:
    #
    #   > Each combination of app and store is given a bucket of 1000 cost points, with a leak rate
    #   > of 50 cost points per second. This means that the total cost of your queries cannot exceed
    #   > 1,000 points at any given time, and that room is created in the app’s bucket at a rate of
    #   > 50 points per second.
    #
    #     Sidekiq::Limiter.points(:shopify, 1000, 20)
    #
    # Options:
    #   :ttl - time for the data to live in Redis, default 24 hours
    #   :wait_timeout - seconds to wait for the rate limit or raises a
    #     Sidekiq::Limiter::OverLimit, 0 means never wait, default 5
    #   :policy - what should the API do if rate limit cannot be met, legal values: [:raise, :skip],
    #     :raise will raise Sidekiq::Limiter::OverLimit, :skip will return without executing the block,
    #     defaults to :raise
    #   :backoff - a Proc(limiter, job, ex) which calculates an integer number of seconds to pause before retrying in case of OverLimit
    #
    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#280
    def points(name, count, interval, options = T.unsafe(nil)); end

    # @raise [ArgumentError]
    #
    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#99
    def redis(&block); end

    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#88
    def redis=(pool); end

    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#118
    def redis_pool; end

    # Provide a simple unlimited rate limiter for test environments and bypassing
    # an existing rate limit in certain cases.  Allow any args so it can
    # dynamically swap with a real limiter.
    #
    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#316
    def unlimited(*args); end

    # Register a sliding-window-based rate limiter within Redis.  The window can be
    # per :second, :minute, :hour or :day.
    #
    # Limit banking operations to 10 per second:
    #
    #     Sidekiq::Limiter.window(:banking, 10, :second)
    #
    # Options:
    #   :ttl - time for the data to live in Redis, default 90 days
    #   :wait_timeout - seconds to wait for the rate limit or raises a
    #     Sidekiq::Limiter::OverLimit, 0 means never wait, default 5
    #   :policy - what should the API do if rate limit cannot be met, legal values: [:raise, :skip],
    #     :raise will raise Sidekiq::Limiter::OverLimit, :skip will return without executing the block,
    #     defaults to :raise
    #   :backoff - a Proc(limiter, job, ex) which calculates an integer number of seconds to pause before retrying in case of OverLimit
    #
    # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#306
    def window(name, count, interval, options = T.unsafe(nil)); end
  end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/base.rb#3
class Sidekiq::Limiter::Base
  # @raise [ArgumentError]
  # @return [Base] a new instance of Base
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/base.rb#6
  def initialize(name, options); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/base.rb#21
  def backoff; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/base.rb#13
  def key; end

  # Returns the value of attribute name.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/base.rb#4
  def name; end

  # Returns the value of attribute options.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/base.rb#4
  def options; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/base.rb#41
  def pause(length); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/base.rb#29
  def policy; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/base.rb#33
  def reschedule; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/base.rb#17
  def status; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/base.rb#37
  def to_s; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/base.rb#25
  def ttl; end

  # Returns the value of attribute wait_for.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/base.rb#4
  def wait_for; end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/bucket.rb#8
class Sidekiq::Limiter::Bucket < ::Sidekiq::Limiter::Base
  # Create a rate limiter of +size+ per +interval+, e.g. 5 per second.
  #
  # Resets at the start of each interval so it's possible to perform
  # more than +size+ operations in a given interval, e.g. you can perform 5
  # operations at 12:03:58.999 and then another 5 operations at 12:03:59.001
  # since the interval resets at 12:03:59.000.
  #
  # Name should be a URL-safe descriptor, i.e. "user_12345", not "Bob's Rate".
  #
  # @raise [ArgumentError]
  # @return [Bucket] a new instance of Bucket
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/bucket.rb#23
  def initialize(name, size, interval, options); end

  # Returns the value of attribute size.
  # deprecated
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/bucket.rb#11
  def count; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/bucket.rb#31
  def establish; end

  # Returns the value of attribute interval.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/bucket.rb#11
  def interval; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/bucket.rb#45
  def key; end

  # Returns the value of attribute size.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/bucket.rb#11
  def size; end

  # Yield if the current interval has not gone over limit.
  # :used is the number of points used by this call, defaulting to 1.
  #
  # If this is a :second-based limiter, will +sleep+ up to
  # +wait_timeout+ seconds until it can fit within limit or
  # raise Sidekiq::Limiter::OverLimit.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/bucket.rb#56
  def within_limit(used: T.unsafe(nil)); end

  private

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/bucket.rb#112
  def bucket_name; end

  # How long the bucket data will persist.
  # Note that we store all bucket data for one time
  # period larger than the interval.  If this is a
  # :second bucket, we'll store 60 buckets of data for
  # a minute of data.  If this is an :hour bucket, we'll
  # store 24 buckets for a day of data.
  #
  # This gives us recent usage history that we can display
  # in the Web UI without having to worry about truly
  # long term storage.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/bucket.rb#103
  def data_ttl; end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/bucket.rb#9
Sidekiq::Limiter::Bucket::INTERVALS = T.let(T.unsafe(nil), Set)

# A concurrent limiter allows a block to execute iff it can
# obtain a token. It tracks the following metrics:
#
# - Number of times a thread got a token immediately
# - Number of times a thread had to wait for a token
# - Number of times a thread could not get a token.
# - Number of times a thread held a token for more than the locktime
# - Total wait time to get a token
# - Total held time for a token
#
# +name+ should be a URL-safe descriptor, i.e. "user_12345", not "Bob's Rate".
# +policy+ can be :raise (default) to raise OverLimit if a token cannot be obtained within +wait_timeout+,
#   or :ignore if the block should be skipped if the rate limit can't be fulfilled.
#
# source://sidekiq-ent//lib/sidekiq-ent/limiter/concurrent.rb#24
class Sidekiq::Limiter::Concurrent < ::Sidekiq::Limiter::Base
  # @raise [ArgumentError]
  # @return [Concurrent] a new instance of Concurrent
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/concurrent.rb#27
  def initialize(name, size, options); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/concurrent.rb#38
  def establish; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/concurrent.rb#54
  def key; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/concurrent.rb#50
  def lock_for; end

  # Returns the value of attribute size.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/concurrent.rb#25
  def size; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/concurrent.rb#58
  def within_limit; end

  private

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/concurrent.rb#94
  def lock; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/concurrent.rb#81
  def unlock(lockdata, holdstart); end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#126
Sidekiq::Limiter::DEFAULT_BACKOFF = T.let(T.unsafe(nil), Proc)

# source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#56
Sidekiq::Limiter::DEFAULT_OPTIONS = T.let(T.unsafe(nil), Hash)

# source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#55
Sidekiq::Limiter::DEFAULT_RESCHEDULE = T.let(T.unsafe(nil), Integer)

# source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#54
Sidekiq::Limiter::DEFAULT_TTL = T.let(T.unsafe(nil), Integer)

# source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#52
Sidekiq::Limiter::LEGAL_NAME = T.let(T.unsafe(nil), Regexp)

# Implements a leaky bucket rate limiter.
#
# Each limiter is bucket which holds X drops. The bucket
# drains in Y seconds, a drop every (Y/X) seconds. Callers
# may fill up the bucket as fast as they want but once full,
# future calls will be throttled based on the drain rate.
#
# source://sidekiq-ent//lib/sidekiq-ent/limiter/leaky.rb#12
class Sidekiq::Limiter::LeakyBucket < ::Sidekiq::Limiter::Base
  # @raise [ArgumentError]
  # @return [LeakyBucket] a new instance of LeakyBucket
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/leaky.rb#15
  def initialize(name, size, interval, options); end

  # Returns the value of attribute interval.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/leaky.rb#13
  def interval; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/leaky.rb#23
  def key; end

  # Returns the value of attribute size.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/leaky.rb#13
  def size; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/leaky.rb#27
  def within_limit; end

  private

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/leaky.rb#75
  def to_sec(val); end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/leaky.rb#53
class Sidekiq::Limiter::LeakyBucket::Result
  # @return [Result] a new instance of Result
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/leaky.rb#55
  def initialize(limiter, next_drip); end

  # Returns the value of attribute limiter.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/leaky.rb#54
  def limiter; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/leaky.rb#60
  def method_missing(*args); end

  # Returns the value of attribute next_drip.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/leaky.rb#54
  def next_drip; end

  private

  # @return [Boolean]
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/leaky.rb#68
  def respond_to_missing?(name); end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/middleware.rb#5
class Sidekiq::Limiter::Middleware
  include ::Sidekiq::ServerMiddleware

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/middleware.rb#8
  def call(inst, job, queue); end

  private

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/middleware.rb#47
  def maximum_reschedules(limiter, job); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/middleware.rb#31
  def reschedule(inst, ex, msg, limiter, copy_of_args); end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#64
class Sidekiq::Limiter::OverLimit < ::RuntimeError
  # @return [OverLimit] a new instance of OverLimit
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#66
  def initialize(limiter); end

  # Returns the value of attribute limiter.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#65
  def limiter; end

  # Sets the attribute limiter
  #
  # @param value the value to set the attribute limiter to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#65
  def limiter=(_arg0); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter.rb#70
  def to_s; end
end

# Implements a points-based rate limiter.
#
# This is an implementation of the leaky-bucket algorithm, wherein a
# bucket of fixed size is filled with points at a given rate. Each operation
# is associated with a cost, and the operation is only allowed if the total cost
# of the operation is less than or equal to the current number of points in the bucket.
#
# Caller must provide an estimate of the expected cost in points and then use `points_used`
# to report the actual number of points consumed. The remote service will typically respond
# with the points consumed, e.g. via an HTTP Response Header or within the response payload.
#
#   limiter.within_limit(estimate: 400) do |result|
#     # make call
#     actual_pts = 300
#     result.points_used(actual_pts)
#   end
#
# To be clear, `points_used` is strictly optional. Using it ensures Sidekiq doesn't prematurely
# limit your calls if you are overestimating the cost.
#
# source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#27
class Sidekiq::Limiter::Points < ::Sidekiq::Limiter::Base
  # @raise [ArgumentError]
  # @return [Points] a new instance of Points
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#30
  def initialize(name, size, interval, options = T.unsafe(nil)); end

  # Returns the value of attribute interval.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#28
  def interval; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#38
  def key; end

  # Returns the value of attribute size.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#28
  def size; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#42
  def within_limit(estimate:); end

  private

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#132
  def to_sec(val); end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#85
class Sidekiq::Limiter::Points::Result
  # @return [Result] a new instance of Result
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#88
  def initialize(limiter, wait_time, estimate, points_left); end

  # Returns the value of attribute actual.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#86
  def actual; end

  # This is realtime data and can change at any moment based
  # on usage from other jobs/threads.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#109
  def current_points; end

  # Returns the value of attribute estimate.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#86
  def estimate; end

  # Returns the value of attribute limiter.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#86
  def limiter; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#113
  def method_missing(*args); end

  # Returns the value of attribute points_left.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#86
  def points_left; end

  # After making the call to the remote side which consumes the points,
  # call this method with the actual points consumed so the points tracking
  # is as accurate as possible.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#99
  def points_used(actual_pts); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#125
  def to_s; end

  # Returns the value of attribute wait_time.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#86
  def wait_time; end

  private

  # @return [Boolean]
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/points.rb#121
  def respond_to_missing?(name); end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#37
class Sidekiq::Limiter::Status
  # @raise [ArgumentError]
  # @return [Status] a new instance of Status
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#245
  def initialize(key); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#253
  def helper; end

  # Returns the value of attribute key.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#243
  def key; end

  # Sets the attribute key
  #
  # @param value the value to set the attribute key to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#243
  def key=(_arg0); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#269
  def method_missing(*args); end

  # Returns the value of attribute name.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#243
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#243
  def name=(_arg0); end

  private

  # @return [Boolean]
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#277
  def respond_to_missing?(name); end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#125
class Sidekiq::Limiter::Status::Bucket
  # @return [Bucket] a new instance of Bucket
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#128
  def initialize(key, name); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#149
  def history; end

  # Returns the value of attribute interval.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#126
  def interval; end

  # Sets the attribute interval
  #
  # @param value the value to set the attribute interval to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#126
  def interval=(_arg0); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#137
  def rate; end

  # Returns the value of attribute size.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#126
  def size; end

  # Sets the attribute size
  #
  # @param value the value to set the attribute size to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#126
  def size=(_arg0); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#141
  def type; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#145
  def type_name; end

  private

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#172
  def bucket_name(time = T.unsafe(nil)); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#193
  def data_count; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#184
  def increment; end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#38
class Sidekiq::Limiter::Status::Concurrent
  # @return [Concurrent] a new instance of Concurrent
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#41
  def initialize(key, name); end

  # Returns the value of attribute available.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#39
  def available; end

  # Sets the attribute available
  #
  # @param value the value to set the attribute available to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#39
  def available=(_arg0); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#65
  def available_pct; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#73
  def held; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#77
  def held_time; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#81
  def immediate; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#97
  def overtime; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#53
  def rate; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#85
  def reclaimed; end

  # Returns the value of attribute size.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#39
  def size; end

  # Sets the attribute size
  #
  # @param value the value to set the attribute size to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#39
  def size=(_arg0); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#57
  def type; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#61
  def type_name; end

  # Returns the value of attribute used.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#39
  def used; end

  # Sets the attribute used
  #
  # @param value the value to set the attribute used to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#39
  def used=(_arg0); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#69
  def used_pct; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#93
  def wait_time; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#89
  def waited; end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#203
class Sidekiq::Limiter::Status::LeakyBucket
  # @return [LeakyBucket] a new instance of LeakyBucket
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#205
  def initialize(key, name); end

  # Returns the value of attribute drops.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#204
  def drops; end

  # Returns the value of attribute hit.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#204
  def hit; end

  # Returns the value of attribute interval.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#204
  def interval; end

  # Returns the value of attribute miss.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#204
  def miss; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#218
  def rate; end

  # Returns the value of attribute size.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#204
  def size; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#210
  def type; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#214
  def type_name; end

  # Returns the value of attribute waited.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#204
  def waited; end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#223
class Sidekiq::Limiter::Status::Points
  # @return [Points] a new instance of Points
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#225
  def initialize(key, name); end

  # Returns the value of attribute hit.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#224
  def hit; end

  # Returns the value of attribute interval.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#224
  def interval; end

  # Returns the value of attribute miss.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#224
  def miss; end

  # Returns the value of attribute points.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#224
  def points; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#238
  def rate; end

  # Returns the value of attribute size.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#224
  def size; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#230
  def type; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#234
  def type_name; end

  # Returns the value of attribute waited.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#224
  def waited; end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#102
class Sidekiq::Limiter::Status::Window
  # @return [Window] a new instance of Window
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#104
  def initialize(key, name); end

  # Returns the value of attribute interval.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#103
  def interval; end

  # Sets the attribute interval
  #
  # @param value the value to set the attribute interval to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#103
  def interval=(_arg0); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#112
  def rate; end

  # Returns the value of attribute size.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#103
  def size; end

  # Sets the attribute size
  #
  # @param value the value to set the attribute size to.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#103
  def size=(_arg0); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#116
  def type; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#120
  def type_name; end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/unlimited.rb#3
class Sidekiq::Limiter::Unlimited < ::Sidekiq::Limiter::Base
  # @return [Unlimited] a new instance of Unlimited
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/unlimited.rb#6
  def initialize(*args); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/unlimited.rb#20
  def key; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/unlimited.rb#10
  def within_limit(*args, **kwargs, &block); end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/unlimited.rb#4
Sidekiq::Limiter::Unlimited::NONE = T.let(T.unsafe(nil), Hash)

# source://sidekiq-ent//lib/sidekiq-ent/limiter/unlimited.rb#24
class Sidekiq::Limiter::Unlimited::ResultStub
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/unlimited.rb#29
  def method_missing(*_arg0); end

  private

  # @return [Boolean]
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/unlimited.rb#25
  def respond_to_missing?(*_arg0); end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/window.rb#8
class Sidekiq::Limiter::Window < ::Sidekiq::Limiter::Base
  # Create a rate limiter of +size+ per +interval+, e.g. 5 per second.
  # +interval+ may be a symbol (:second, :minute) or an integer number
  # of seconds.
  #
  # This implements a "sliding window" limiter so you cannot perform
  # more than N operations until a full interval has passed.
  #
  # Name should be a URL-safe descriptor, i.e. "user_12345", not "Bob's Rate".
  #
  # Options:
  #   :wait_timeout - maximum time to pause while waiting for an available bucket, only applicable
  #               to :second buckets only.
  #
  # @return [Window] a new instance of Window
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/window.rb#27
  def initialize(name, size, interval, options); end

  # Returns the value of attribute bucket.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/window.rb#11
  def bucket; end

  # Returns the value of attribute size.
  # deprecated
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/window.rb#11
  def count; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/window.rb#49
  def establish; end

  # Returns the value of attribute interval.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/window.rb#11
  def interval; end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/window.rb#63
  def key; end

  # Returns the value of attribute size.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/window.rb#11
  def size; end

  # Yield if the current interval has not gone over quota.
  # :used is the number of points used by this call, defaulting to 1.
  #
  # If this is a :second-based limiter, will +sleep+ up to
  # +wait_timeout+ seconds until it can fit within quota or
  # raise Sidekiq::Limiter::OverLimit.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/limiter/window.rb#74
  def within_limit(used: T.unsafe(nil)); end
end

# source://sidekiq-ent//lib/sidekiq-ent/limiter/window.rb#9
Sidekiq::Limiter::Window::INTERVALS = T.let(T.unsafe(nil), Set)

# source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#4
class Sidekiq::LimiterSet
  include ::Enumerable

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#7
  def each(&block); end

  # source://sidekiq-ent//lib/sidekiq-ent/limiter/status.rb#15
  def paginate(cursor, filter, &block); end
end

# source://sidekiq-ent//lib/sidekiq-ent.rb#21
Sidekiq::NAME = T.let(T.unsafe(nil), String)

# source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#27
module Sidekiq::Periodic; end

# source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#49
class Sidekiq::Periodic::Loop
  # @return [Loop] a new instance of Loop
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#52
  def initialize(lid); end

  # returns [jid, epoch integer] pairs for each execution
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#75
  def history; end

  # Returns the value of attribute klass.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#50
  def klass; end

  # Returns the value of attribute lid.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#50
  def lid; end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#64
  def next_run; end

  # Returns the value of attribute options.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#50
  def options; end

  # Returns the value of attribute schedule.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#50
  def schedule; end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#68
  def time_source; end

  # Returns the value of attribute tz_name.
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#50
  def tz_name; end
end

# source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#28
class Sidekiq::Periodic::LoopSet
  include ::Enumerable

  # @return [LoopSet] a new instance of LoopSet
  #
  # source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#31
  def initialize; end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#42
  def each; end

  # source://sidekiq-ent//lib/sidekiq-ent/periodic.rb#38
  def size; end
end
