# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WebhookArea::ApplicationController`.
# Please instead update this file by running `bin/tapioca dsl WebhookArea::ApplicationController`.


class WebhookArea::ApplicationController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
