variables:
  RUBY_VERSION: 'ruby-3.3.6-slim'
  RUBY_IMAGE: containers.l.twogate.net/docker/ruby-slim-for-rails:ruby3.3.6
  POSTGRES_VERSION: 'postgres:15-alpine'

cache: &cache
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/bundle
    # - public/vite
    # - tmp/cache/vite

stages:
  - prepare
  - test
  - post-test
  - build
  - pre-deploy
  - deploy

# arm64 環境で動かす
.arm64_tags: &arm64_tags
  tags:
   - arm64
   - linux

bundle-package:
  <<: *arm64_tags
  image: ${RUBY_IMAGE}
  stage: prepare
  cache:
    <<: *cache
  script:
    - bundle install --jobs=`nproc` --deployment
    - bundle clean
  except:
    - /^deploy-.*$/
    - schedules

include:
  - template: Security/SAST.gitlab-ci.yml
sast:
  stage: post-test
brakeman-sast:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
nodejs-scan-sast:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
semgrep-sast:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

rubocop:
  <<: *arm64_tags
  image: ${RUBY_IMAGE}
  stage: test
  cache:
    <<: *cache
    policy: pull
  variables:
    RAILS_ENV: test
    ALLOW_ORIGINS: '[]'
  before_script:
    - /bin/sh docker/scripts/bundle_install.sh
  script:
    - bundle exec rubocop -DESP
  except:
    - /^deploy-.*$/
    - schedules

rspec:
  <<: *arm64_tags
  # parallel: 5
  image: ${RUBY_IMAGE}
  stage: test
  cache:
    <<: *cache
    policy: pull
  variables:
    RAILS_ENV: test
    POSTGRES_TEST_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    REDIS_URL: redis://redis:6379/0
    ALLOW_ORIGINS: '[]'
    # PARALLEL_SPLIT_TEST: 'true'
    # PARALLEL_TESTS_CONCURRENCY: 4
    # KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC: $KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC
    # KNAPSACK_PRO_FIXED_QUEUE_SPLIT: 'true'
    # KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES: 'true'
  services:
    - ${POSTGRES_VERSION}
    - redis:7.0-alpine
    # - name: containers.l.twogate.net/docker/cassandra:3.11
    #   alias: cassandra
    # - name: amazon/dynamodb-local
    #   alias: dynamodb
  before_script:
    - touch log/bullet.log
    - /bin/sh docker/scripts/bundle_install.sh
    - bundle exec rake db:setup
    # - bundle exec rake parallel:setup
    # - bundle exec thor dynamodb:migrate
  after_script:
    - cat log/bullet.log
  script:
    - bundle exec rspec
    # - export KNAPSACK_PRO_CI_NODE_TOTAL=$CI_NODE_TOTAL
    # - export KNAPSACK_PRO_CI_NODE_INDEX=$(expr $CI_NODE_INDEX - 1)
    # - bundle exec parallel_rspec -n $PARALLEL_TESTS_CONCURRENCY -e './bin/parallel_tests'
  except:
    - /^deploy-.*$/
    - schedules

sorbet:
  <<: *arm64_tags
  image: ${RUBY_IMAGE}
  stage: test
  cache:
    <<: *cache
    key: ${CI_JOB_IMAGE}-test
    policy: pull-push
  services:
    - ${POSTGRES_VERSION}
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_TEST_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    RAILS_ENV: development
  before_script:
    - mv vendor/bundle /usr/local/ || true
    - RAILS_ENV=development /bin/sh docker/scripts/bundle_install.sh
    - bundle exec rake db:create db:schema:load
  script:
    - bundle exec tapioca gems -w `nproc` --verify --environment=development
    - bundle exec tapioca dsl -w `nproc` --verify --environment=development
    - bundle exec srb tc
    - bundle exec tapioca check-shims -w `nproc`
    - mv /usr/local/bundle vendor/
  except:
    - /^deploy-.*$/
    - schedules

assets:precompile:
  <<: *arm64_tags
  image: ${RUBY_IMAGE}
  stage: test
  cache:
    <<: *cache
  variables:
    RAILS_ENV: production
    SECRET_KEY_BASE: 784a47d74a21582374648c380d4d2445514133912f2a075d47d1bba5391487c12e78e5e746e838bf227a7855388003748bd20abf5fd151710d15dab58736d35e
  script:
    - /bin/sh docker/scripts/bundle_install.sh
    - yarn install
    - bundle exec rails assets:precompile --trace
  artifacts:
    expire_in: 1d
    paths:
      - public/vite
  only:
    - /^deploy-.*$/
  except:
    - schedules

build:app:staging:
  <<: *arm64_tags
  image: containers.l.twogate.net/docker/docker-awscli:master
  stage: build
  cache:
    <<: *cache
    policy: pull
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    BUNDLE_GIT__L__TWOGATE__NET: $BUNDLE_GIT__L__TWOGATE__NET
  script:
    - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 287511440462.dkr.ecr.ap-northeast-1.amazonaws.com
    - docker build . -f docker/Dockerfile -t rails_app:latest --build-arg BUNDLE_GIT__L__TWOGATE__NET --build-arg BUNDLE_ENTERPRISE__CONTRIBSYS__COM
    - docker tag rails_app:latest 287511440462.dkr.ecr.ap-northeast-1.amazonaws.com/id-platform-main-app-stg:latest
    - docker tag rails_app:latest 287511440462.dkr.ecr.ap-northeast-1.amazonaws.com/id-platform-main-app-stg:$CI_COMMIT_SHA
    - docker push 287511440462.dkr.ecr.ap-northeast-1.amazonaws.com/id-platform-main-app-stg:latest
    - docker push 287511440462.dkr.ecr.ap-northeast-1.amazonaws.com/id-platform-main-app-stg:$CI_COMMIT_SHA
  only:
    - deploy-staging
  except:
    - schedules

build:app:production:
  <<: *arm64_tags
  image: containers.l.twogate.net/docker/docker-awscli:master
  stage: build
  cache:
    <<: *cache
    policy: pull
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    BUNDLE_GIT__L__TWOGATE__NET: $BUNDLE_GIT__L__TWOGATE__NET
  script:
    - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 843188904699.dkr.ecr.ap-northeast-1.amazonaws.com
    - docker build . -f docker/Dockerfile -t rails_app:latest --build-arg BUNDLE_GIT__L__TWOGATE__NET --build-arg BUNDLE_ENTERPRISE__CONTRIBSYS__COM
    - docker tag rails_app:latest 843188904699.dkr.ecr.ap-northeast-1.amazonaws.com/id-platform-main-app-prod:latest
    - docker tag rails_app:latest 843188904699.dkr.ecr.ap-northeast-1.amazonaws.com/id-platform-main-app-prod:$CI_COMMIT_SHA
    - docker push 843188904699.dkr.ecr.ap-northeast-1.amazonaws.com/id-platform-main-app-prod:latest
    - docker push 843188904699.dkr.ecr.ap-northeast-1.amazonaws.com/id-platform-main-app-prod:$CI_COMMIT_SHA
  only:
    - deploy-production
  except:
    - schedules

# ------------------------------------------------------------------------------
# Deploy Development
# ------------------------------------------------------------------------------
deploy-dev:
  stage: deploy
  image: ${RUBY_IMAGE}
  cache: {}
  variables:
    RAILS_ENV: production
    FLY_ACCESS_TOKEN: $FLY_ACCESS_TOKEN
  script:
    - curl -L https://fly.io/install.sh | sh
    - ~/.fly/bin/flyctl deploy -c fly.toml
  only:
    - deploy-flyio
  except:
    - schedules

# ------------------------------------------------------------------------------
# Deploy Staging jobs
# ------------------------------------------------------------------------------
.deploy:staging:base: &deploy-staging-base
  image: containers.l.twogate.net/docker/ecspresso:master
  cache: {}
  variables:
    AWS_ASSUME_ROLE_ARN: arn:aws:iam::287511440462:role/ecspresso-ecs-role
  before_script:
    - STS=`aws sts assume-role --role-arn $AWS_ASSUME_ROLE_ARN --role-session-name ecspresso-$CI_PROJECT_ID-$CI_JOB_ID`;export AWS_ACCESS_KEY_ID=`echo "${STS}" | jq -r '.Credentials.AccessKeyId'`;export AWS_SECRET_ACCESS_KEY=`echo "${STS}" | jq -r '.Credentials.SecretAccessKey'`;export AWS_SESSION_TOKEN=`echo "${STS}" | jq -r '.Credentials.SessionToken'`
  only:
    - deploy-staging
  except:
    - schedules

🔍 pre-deploy:diff:app:staging:
  <<: *deploy-staging-base
  stage: pre-deploy
  script:
    - ecspresso diff --color --ext-str APP_IMAGE_TAG=$CI_COMMIT_SHA --config ecspresso/stg/services/app/config.yaml

👍 pre-deploy:approval:staging:
  <<: *deploy-staging-base
  stage: pre-deploy
  script:
    - ecspresso deploy --dry-run --ext-str APP_IMAGE_TAG=$CI_COMMIT_SHA --config ecspresso/stg/services/app/config.yaml
  when: manual

🔧 deploy:migration:staging:
  <<: *deploy-staging-base
  stage: deploy
  script:
    - ecspresso run --watch-container app --ext-str APP_IMAGE_TAG=$CI_COMMIT_SHA --config ecspresso/stg/tasks/config.yaml --task-def ecspresso/stg/tasks/oneshot-task-def.jsonnet --overrides '{"containerOverrides":[{"name":"app","command":["bundle","exec","rails","ridgepole:apply"]}]}'
  needs:
    - job: 👍 pre-deploy:approval:staging
      artifacts: false

🚀 deploy:app:staging:
  <<: *deploy-staging-base
  stage: deploy
  script:
    - ecspresso deploy --ext-str APP_IMAGE_TAG=$CI_COMMIT_SHA --config ecspresso/stg/services/app/config.yaml
  needs:
    - job: 👍 pre-deploy:approval:staging
      artifacts: false
    - job: 🔧 deploy:migration:staging
      artifacts: false

🚀 deploy:worker:staging:
  <<: *deploy-staging-base
  stage: deploy
  script:
    - ecspresso deploy --ext-str APP_IMAGE_TAG=$CI_COMMIT_SHA --config ecspresso/stg/services/worker/config.yaml
  needs:
    - job: 👍 pre-deploy:approval:staging
      artifacts: false
    - job: 🔧 deploy:migration:staging
      artifacts: false


# ------------------------------------------------------------------------------
# Deploy Production jobs
# ------------------------------------------------------------------------------
.deploy:production:base: &deploy-production-base
  image: containers.l.twogate.net/docker/ecspresso:master
  cache: {}
  variables:
    AWS_ASSUME_ROLE_ARN: arn:aws:iam::843188904699:role/ecspresso-ecs-role
  before_script:
    - STS=`aws sts assume-role --role-arn $AWS_ASSUME_ROLE_ARN --role-session-name ecspresso-$CI_PROJECT_ID-$CI_JOB_ID`;export AWS_ACCESS_KEY_ID=`echo "${STS}" | jq -r '.Credentials.AccessKeyId'`;export AWS_SECRET_ACCESS_KEY=`echo "${STS}" | jq -r '.Credentials.SecretAccessKey'`;export AWS_SESSION_TOKEN=`echo "${STS}" | jq -r '.Credentials.SessionToken'`
  only:
    - deploy-production
  except:
    - schedules

🔍 pre-deploy:diff:app:production:
  <<: *deploy-production-base
  stage: pre-deploy
  script:
    - ecspresso diff --color --ext-str APP_IMAGE_TAG=$CI_COMMIT_SHA --config ecspresso/prod/services/app/config.yaml

👍 pre-deploy:approval:production:
  <<: *deploy-production-base
  stage: pre-deploy
  script:
    - ecspresso deploy --dry-run --ext-str APP_IMAGE_TAG=$CI_COMMIT_SHA --config ecspresso/prod/services/app/config.yaml
  when: manual

🔧 deploy:migration:production:
  <<: *deploy-production-base
  stage: deploy
  script:
    - ecspresso run --watch-container app --ext-str APP_IMAGE_TAG=$CI_COMMIT_SHA --config ecspresso/prod/tasks/config.yaml --task-def ecspresso/prod/tasks/oneshot-task-def.jsonnet --overrides '{"containerOverrides":[{"name":"app","command":["bundle","exec","rails","ridgepole:apply"]}]}'
  needs:
    - job: 👍 pre-deploy:approval:production
      artifacts: false

🚀 deploy:app:production:
  <<: *deploy-production-base
  stage: deploy
  script:
    - ecspresso deploy --ext-str APP_IMAGE_TAG=$CI_COMMIT_SHA --config ecspresso/prod/services/app/config.yaml
  needs:
    - job: 👍 pre-deploy:approval:production
      artifacts: false
    - job: 🔧 deploy:migration:production
      artifacts: false

🚀 deploy:worker:production:
  <<: *deploy-production-base
  stage: deploy
  script:
    - ecspresso deploy --ext-str APP_IMAGE_TAG=$CI_COMMIT_SHA --config ecspresso/prod/services/worker/config.yaml
  needs:
    - job: 👍 pre-deploy:approval:production
      artifacts: false
    - job: 🔧 deploy:migration:production
      artifacts: false
