# fly.toml app configuration file generated for auth-platform on 2023-05-04T19:52:55+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "auth-platform"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "docker/Dockerfile"
  [build.args]
    RAILS_ENV = "production"

[env]
  PRIMARY_REGION = "nrt"
  RUBY_YJIT_ENABLE = 1

[processes]
  #sidekiq = "bundle exec sidekiq"
  web = "bundle exec rails s -p 3000"

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
