# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AdminArea::ApplicationController`.
# Please instead update this file by running `bin/tapioca dsl AdminArea::ApplicationController`.


class AdminArea::ApplicationController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule

  # Methods from Turbo::Frames::FrameRequest module
  sig { returns(T::Boolean) }
  def turbo_frame_request?; end

  sig { returns(T.nilable(String)) }
  def turbo_frame_request_id; end

  sig { returns(HelperProxy) }
  def helpers; end

  module HelperMethods
    include ::Turbo::DriveHelper
    include ::Turbo::FramesHelper
    include ::Turbo::IncludesHelper
    include ::Turbo::StreamsHelper
    include ::ActionView::Helpers::CaptureHelper
    include ::ActionView::Helpers::OutputSafetyHelper
    include ::ActionView::Helpers::TagHelper
    include ::Turbo::Streams::ActionHelper
    include ::ViteRails::TagHelpers
    include ::ActionController::Base::HelperMethods
    include ::ApplicationHelper
    include ::Pagy::UrlHelpers
    include ::Pagy::Frontend
    include ::AdminArea::ApplicationHelper
  end

  class HelperProxy < ::ActionView::Base
    include HelperMethods
  end
end
