# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AdminArea::DeliveriesController`.
# Please instead update this file by running `bin/tapioca dsl AdminArea::DeliveriesController`.


class AdminArea::DeliveriesController
  sig { returns(HelperProxy) }
  def helpers; end

  module HelperMethods
    include ::Turbo::DriveHelper
    include ::Turbo::FramesHelper
    include ::Turbo::IncludesHelper
    include ::Turbo::StreamsHelper
    include ::ActionView::Helpers::CaptureHelper
    include ::ActionView::Helpers::OutputSafetyHelper
    include ::ActionView::Helpers::TagHelper
    include ::Turbo::Streams::ActionHelper
    include ::ViteRails::TagHelpers
    include ::ActionController::Base::HelperMethods
    include ::ApplicationHelper
    include ::Pagy::UrlHelpers
    include ::Pagy::Frontend
    include ::AdminArea::ApplicationHelper
    include ::AdminArea::ApplicationController::HelperMethods
    include ::AdminArea::DeliveriesHelper
  end

  class HelperProxy < ::ActionView::Base
    include HelperMethods
  end
end
