# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DeliveryEvent::Type::Sent`.
# Please instead update this file by running `bin/tapioca dsl DeliveryEvent::Type::Sent`.


class DeliveryEvent::Type::Sent
  include GeneratedAttributeMethods

  module GeneratedAttributeMethods
    sig { returns(T.nilable(::String)) }
    def recipient_id; end

    sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
    def recipient_id=(value); end

    sig { returns(T.nilable(::String)) }
    def user_id; end

    sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
    def user_id=(value); end
  end
end
