# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DeliveryEvent::Type::Updated`.
# Please instead update this file by running `bin/tapioca dsl DeliveryEvent::Type::Updated`.


class DeliveryEvent::Type::Updated
  include GeneratedAttributeMethods

  module GeneratedAttributeMethods
    sig { returns(T.nilable(::String)) }
    def changes; end

    sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
    def changes=(value); end
  end
end
