# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Protobuf::Struct`.
# Please instead update this file by running `bin/tapioca dsl Google::Protobuf::Struct`.

class Google::Protobuf::Struct
  sig { params(fields: T.nilable(T.any(Google::Protobuf::RepeatedField[], T::Array[]))).void }
  def initialize(fields: Google::Protobuf::RepeatedField.new(:message, )); end

  sig { void }
  def clear_fields; end

  sig { returns(Google::Protobuf::RepeatedField[]) }
  def fields; end

  sig { params(value: Google::Protobuf::RepeatedField[]).void }
  def fields=(value); end
end
