# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Cloud::RecaptchaEnterprise::V1::AnnotateAssessmentRequest::Annotation`.
# Please instead update this file by running `bin/tapioca dsl Google::Cloud::RecaptchaEnterprise::V1::AnnotateAssessmentRequest::Annotation`.

module Google::Cloud::RecaptchaEnterprise::V1::AnnotateAssessmentRequest::Annotation
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Google::Cloud::RecaptchaEnterprise::V1::AnnotateAssessmentRequest::Annotation::ANNOTATION_UNSPECIFIED = 0
Google::Cloud::RecaptchaEnterprise::V1::AnnotateAssessmentRequest::Annotation::FRAUDULENT = 2
Google::Cloud::RecaptchaEnterprise::V1::AnnotateAssessmentRequest::Annotation::LEGITIMATE = 1
Google::Cloud::RecaptchaEnterprise::V1::AnnotateAssessmentRequest::Annotation::PASSWORD_CORRECT = 3
Google::Cloud::RecaptchaEnterprise::V1::AnnotateAssessmentRequest::Annotation::PASSWORD_INCORRECT = 4
