# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ContactAddressForm`.
# Please instead update this file by running `bin/tapioca dsl ContactAddressForm`.

class ContactAddressForm
  sig { returns(T.untyped) }
  def building; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def building=(value); end

  sig { returns(T.untyped) }
  def city; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def city=(value); end

  sig { returns(T.untyped) }
  def country_code; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def country_code=(value); end

  sig { returns(T.untyped) }
  def id; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def id=(value); end

  sig { returns(T.untyped) }
  def phone_number; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def phone_number=(value); end

  sig { returns(T.untyped) }
  def prefecture_code; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def prefecture_code=(value); end

  sig { returns(T.untyped) }
  def street; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def street=(value); end

  sig { returns(T.untyped) }
  def user_id; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def user_id=(value); end

  sig { returns(T.untyped) }
  def zip_code; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def zip_code=(value); end
end
