# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedPathHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedPathHelpersModule`.

module GeneratedPathHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def admin_area_auth_auth0_callback_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_auth_failure_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_auth_logout_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_login_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_logout_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_root_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_users_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_oauth_login_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_oauth_logout_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_oauth_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_private_userinfo_index_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_api_oauth_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def health_check_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def native_oauth_authorization_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_api_oauth_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_session_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_authorization_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_authorized_application_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_authorized_applications_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_discovery_keys_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_discovery_provider_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_discovery_webfinger_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_introspect_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_revoke_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_token_info_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_token_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_userinfo_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def session_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sessions_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_recede_historical_location_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_refresh_historical_location_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_resume_historical_location_path(*args); end
end
