# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedUrlHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedUrlHelpersModule`.


module GeneratedUrlHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def activities_admin_area_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_auth_auth0_callback_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_auth_failure_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_auth_logout_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_deliveries_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_delivery_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_login_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_logout_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_root_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_ruler_area_tenant_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_template_mail_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_template_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_templates_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_auto_tagging_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_auto_taggings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_contact_address_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_tag_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_tags_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_user_profile_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_user_tag_assignment_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_user_tag_assignments_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_users_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_admin_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_admin_users_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_authentication_logout_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_authentication_password_resets_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_authentication_passwords_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_authentication_sessions_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_email_change_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_me_card_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_me_delivery_address_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_me_delivery_addresses_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_me_profile_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_me_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_membership_contract_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_membership_contracts_credit_card_payments_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_membership_contracts_konbini_payments_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_membership_contracts_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_memberships_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_private_userinfo_index_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_public_membership_group_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_public_membership_groups_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_public_membership_plan_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_public_membership_plans_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_public_membership_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_public_memberships_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_public_tenant_stripe_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def assign_memberships_ruler_area_tenant_membership_group_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def authenticate_api_v1_authentication_mfa_sms_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def bulk_api_v1_internal_membership_contracts_credit_card_payments_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def cancel_admin_area_delivery_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def cancel_admin_area_template_mail_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def cancel_api_v1_internal_membership_contract_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def complete_credit_card_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def complete_off_session_card_api_v1_internal_me_card_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def credit_card_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def datepicker_admin_area_user_auto_taggings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_area_delivery_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_area_template_mail_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_area_user_auto_tagging_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_area_user_billing_address_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_area_user_contact_address_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_area_user_tag_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_area_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_area_user_user_profile_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_area_user_user_tag_assignment_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_profile_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_design_settings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_email_template_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_komoju_records_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_login_spa_application_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_membership_group_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_membership_plan_membership_plan_payment_method_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_membership_plan_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_membership_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_oauth_application_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_oauth_provider_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_shopify_multipass_store_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_stripe_records_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_tenant_komoju_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_tenant_setting_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_tenant_stripe_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def enqueue_ruler_area_sidekiq_jobs_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def health_check_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def history_admin_area_user_user_tag_assignments_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def login_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def logout_sessions_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def logout_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def membership_plan_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def membership_plans_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def mfa_sms_resend_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def mfa_sms_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def my_credit_card_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def my_memberships_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def mypage_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def native_oauth_authorization_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_area_delivery_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_area_template_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_area_user_auto_tagging_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_area_user_billing_address_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_area_user_contact_address_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_area_user_tag_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_area_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_area_user_user_profile_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_credit_card_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_ruler_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_sidekiq_job_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_admin_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_email_template_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_komoju_records_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_login_spa_application_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_membership_group_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_membership_plan_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_membership_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_oauth_application_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_oauth_provider_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_shopify_multipass_store_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_stripe_records_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_tenant_komoju_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_tenant_setting_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_tenant_stripe_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_authorization_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_authorized_application_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_authorized_applications_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_callback_federated_authentications_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_discovery_keys_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_discovery_provider_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_discovery_webfinger_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_introspect_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_redirect_federated_authentications_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_revoke_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_token_info_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_token_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_userinfo_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def off_session_setup_intent_api_v1_internal_me_card_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def pause_admin_area_delivery_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def plan_change_api_v1_internal_membership_contract_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def plan_change_preview_api_v1_internal_membership_contract_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def polling_api_v1_internal_membership_contract_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def preview_admin_area_template_mail_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def preview_ruler_area_tenant_stripe_records_products_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def profile_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def publish_admin_area_delivery_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def publish_admin_area_template_mail_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def purchase_membership_plan_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def relaunch_authorizations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def request_api_v1_authentication_password_resets_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def request_api_v1_internal_email_change_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def reset_sms_ratelimit_admin_area_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def resume_admin_area_delivery_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def root_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_auth_auth0_callback_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_auth_failure_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_auth_logout_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_feature_flags_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_flipper_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_login_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_logout_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_root_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_ruler_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_rulers_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_sidekiq_web_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_admin_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_admins_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_design_settings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_email_template_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_email_templates_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_feature_flags_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_komoju_records_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_komoju_records_accounts_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_login_spa_application_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_login_spa_applications_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_membership_group_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_membership_groups_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_membership_plan_membership_plan_payment_method_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_membership_plan_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_membership_plans_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_membership_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_memberships_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_oauth_application_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_oauth_applications_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_oauth_provider_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_oauth_providers_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_root_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_shopify_multipass_store_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_shopify_multipass_stores_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_stripe_records_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_stripe_records_accounts_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_stripe_records_product_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_stripe_records_products_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_tenant_komoju_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_tenant_setting_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_tenant_settings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_tenant_stripe_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenants_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def schedule_admin_area_template_mail_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def send_api_v1_authentication_mfa_sms_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def send_verification_email_api_v1_authentication_registrations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def send_verification_sms_api_v1_authentication_sms_verify_index_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def setup_intent_api_v1_internal_me_card_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shopify_area_multipass_auth_callback_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shopify_area_multipass_auth_register_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shopify_area_multipass_auth_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shopify_area_webhooks_eventbridge_shopify_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sign_up_phone_number_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sign_up_resend_email_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sign_up_resend_sms_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sign_up_set_password_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sign_up_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sign_up_verify_email_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sign_up_verify_sms_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sync_ruler_area_tenant_stripe_records_products_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def tag_picker_admin_area_user_auto_taggings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def toggle_ruler_area_feature_flags_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def toggle_ruler_area_tenant_feature_flags_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def top_ruler_area_tenant_memberships_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_recede_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_refresh_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_resume_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def unlock_account_locks_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_memberships_ruler_area_tenant_membership_group_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def verify_email_api_v1_authentication_registrations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def verify_sms_api_v1_authentication_sms_verify_index_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webhook_area_komoju_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webhook_area_stripe_url(*args); end
end
