# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedPathHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedPathHelpersModule`.

module GeneratedPathHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def admin_area_auth_auth0_callback_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_auth_failure_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_auth_logout_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_login_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_logout_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_root_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_ruler_area_tenant_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_contact_address_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_user_profile_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_users_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_admin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_admin_users_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_authentication_logout_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_authentication_password_resets_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_authentication_passwords_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_authentication_sessions_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_email_change_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_me_card_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_me_delivery_address_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_me_delivery_addresses_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_me_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_internal_me_profile_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_private_userinfo_index_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def assign_memberships_ruler_area_tenant_memberships_group_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def authenticate_api_v1_authentication_mfa_sms_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_area_user_contact_address_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_area_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_area_user_user_profile_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_email_template_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_login_spa_application_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_membership_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_memberships_group_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_memberships_plan_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_oauth_application_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_shopify_multipass_store_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ruler_area_tenant_tenant_setting_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def health_check_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def logout_sessions_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def native_oauth_authorization_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_area_user_contact_address_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_area_user_user_profile_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_ruler_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_admin_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_email_template_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_login_spa_application_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_membership_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_memberships_group_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_memberships_plan_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_oauth_application_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_shopify_multipass_store_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ruler_area_tenant_tenant_setting_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_authorization_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_authorized_application_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_authorized_applications_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_discovery_keys_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_discovery_provider_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_discovery_webfinger_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_introspect_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_revoke_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_token_info_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_token_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_userinfo_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def preview_ruler_area_tenant_stripe_records_products_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def relaunch_authorizations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def request_api_v1_authentication_password_resets_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def request_api_v1_internal_email_change_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def reset_sms_ratelimit_admin_area_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_auth_auth0_callback_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_auth_failure_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_auth_logout_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_login_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_logout_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_root_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_ruler_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_rulers_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_admin_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_admins_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_email_template_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_email_templates_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_login_spa_application_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_login_spa_applications_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_membership_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_memberships_group_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_memberships_groups_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_memberships_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_memberships_plan_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_memberships_plans_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_oauth_application_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_oauth_applications_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_root_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_shopify_multipass_store_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_shopify_multipass_stores_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_stripe_records_product_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_stripe_records_products_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_tenant_setting_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenant_tenant_settings_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruler_area_tenants_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def send_api_v1_authentication_mfa_sms_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def send_verification_email_api_v1_authentication_registrations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def send_verification_sms_api_v1_authentication_sms_verify_index_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def setup_intent_api_v1_internal_me_card_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shopify_area_multipass_auth_callback_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shopify_area_multipass_auth_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shopify_area_multipass_auth_register_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shopify_area_webhooks_eventbridge_shopify_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sync_ruler_area_tenant_stripe_records_products_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def top_ruler_area_tenant_memberships_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_recede_historical_location_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_refresh_historical_location_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_resume_historical_location_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def unlock_account_locks_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_memberships_ruler_area_tenant_memberships_group_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def verify_email_api_v1_authentication_registrations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def verify_sms_api_v1_authentication_sms_verify_index_path(*args); end
end
