# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedUrlHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedUrlHelpersModule`.

module GeneratedUrlHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def admin_area_auth_auth0_callback_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_auth_failure_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_auth_logout_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_login_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_logout_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_root_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_area_users_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_admin_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_oauth_login_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_oauth_logout_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_oauth_signup_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_private_userinfo_index_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def email_verification_registrations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def health_check_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def native_oauth_authorization_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_password_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_profile_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_registration_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_session_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_authorization_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_authorized_application_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_authorized_applications_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_discovery_keys_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_discovery_provider_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_discovery_webfinger_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_introspect_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_revoke_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_token_info_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_token_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_userinfo_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def passwords_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def profiles_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def send_verification_email_registrations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def session_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sessions_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_recede_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_refresh_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_resume_historical_location_url(*args); end
end
