# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RootRedirectController`.
# Please instead update this file by running `bin/tapioca dsl RootRedirectController`.


class RootRedirectController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
