# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserForm`.
# Please instead update this file by running `bin/tapioca dsl UserForm`.

class UserForm
  sig { returns(T.untyped) }
  def contact_address_form; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def contact_address_form=(value); end

  sig { returns(T.untyped) }
  def user_profile_form; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def user_profile_form=(value); end
end
