# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Api::MethodSettings`.
# Please instead update this file by running `bin/tapioca dsl Google::Api::MethodSettings`.


class Google::Api::MethodSettings < Google::Protobuf::AbstractMessage
  sig do
    params(
      auto_populated_fields: T.nilable(T.any(Google::Protobuf::RepeatedField[String], T::Array[String])),
      long_running: T.nilable(Google::Api::MethodSettings::LongRunning),
      selector: T.nilable(String)
    ).void
  end
  def initialize(auto_populated_fields: T.unsafe(nil), long_running: nil, selector: nil); end

  sig { returns(Google::Protobuf::RepeatedField[String]) }
  def auto_populated_fields; end

  sig { params(value: Google::Protobuf::RepeatedField[String]).void }
  def auto_populated_fields=(value); end

  sig { void }
  def clear_auto_populated_fields; end

  sig { void }
  def clear_long_running; end

  sig { void }
  def clear_selector; end

  sig { returns(Object) }
  def has_long_running?; end

  sig { returns(T.nilable(Google::Api::MethodSettings::LongRunning)) }
  def long_running; end

  sig { params(value: T.nilable(Google::Api::MethodSettings::LongRunning)).void }
  def long_running=(value); end

  sig { returns(String) }
  def selector; end

  sig { params(value: String).void }
  def selector=(value); end
end
