# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserArea::ProfilesController`.
# Please instead update this file by running `bin/tapioca dsl UserArea::ProfilesController`.


class UserArea::ProfilesController
  sig { returns(HelperProxy) }
  def helpers; end

  module HelperMethods
    include ::Turbo::DriveHelper
    include ::Turbo::FramesHelper
    include ::Turbo::IncludesHelper
    include ::Turbo::StreamsHelper
    include ::ActionView::Helpers::CaptureHelper
    include ::ActionView::Helpers::OutputSafetyHelper
    include ::ActionView::Helpers::TagHelper
    include ::Turbo::Streams::ActionHelper
    include ::ViteRails::TagHelpers
    include ::ActionController::Base::HelperMethods
    include ::UserAreaHelper
    include ::UserArea::ApplicationController::HelperMethods

    sig { params(table_name: T.untyped, field: T.untyped).returns(T.untyped) }
    def field_editable?(table_name, field); end
  end

  class HelperProxy < ::ActionView::Base
    include HelperMethods
  end
end
