# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Cloud::RecaptchaEnterprise::V1::AccountDefenderAssessment`.
# Please instead update this file by running `bin/tapioca dsl Google::Cloud::RecaptchaEnterprise::V1::AccountDefenderAssessment`.

class Google::Cloud::RecaptchaEnterprise::V1::AccountDefenderAssessment
  sig do
    params(
      labels: T.nilable(T.any(Google::Protobuf::RepeatedField[T.any(Symbol, Integer)], T::Array[T.any(Symbol, Integer)]))
    ).void
  end
  def initialize(labels: T.unsafe(nil)); end

  sig { void }
  def clear_labels; end

  sig { returns(Google::Protobuf::RepeatedField[T.any(Symbol, Integer)]) }
  def labels; end

  sig { params(value: Google::Protobuf::RepeatedField[T.any(Symbol, Integer)]).void }
  def labels=(value); end
end
