# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Cloud::RecaptchaEnterprise::V1::AndroidKeySettings`.
# Please instead update this file by running `bin/tapioca dsl Google::Cloud::RecaptchaEnterprise::V1::AndroidKeySettings`.

class Google::Cloud::RecaptchaEnterprise::V1::AndroidKeySettings
  sig do
    params(
      allow_all_package_names: T.nilable(T::Boolean),
      allowed_package_names: T.nilable(T.any(Google::Protobuf::RepeatedField[String], T::Array[String]))
    ).void
  end
  def initialize(allow_all_package_names: nil, allowed_package_names: T.unsafe(nil)); end

  sig { returns(T::Boolean) }
  def allow_all_package_names; end

  sig { params(value: T::Boolean).void }
  def allow_all_package_names=(value); end

  sig { returns(Google::Protobuf::RepeatedField[String]) }
  def allowed_package_names; end

  sig { params(value: Google::Protobuf::RepeatedField[String]).void }
  def allowed_package_names=(value); end

  sig { void }
  def clear_allow_all_package_names; end

  sig { void }
  def clear_allowed_package_names; end
end
