# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Cloud::RecaptchaEnterprise::V1::AnnotateAssessmentRequest`.
# Please instead update this file by running `bin/tapioca dsl Google::Cloud::RecaptchaEnterprise::V1::AnnotateAssessmentRequest`.

class Google::Cloud::RecaptchaEnterprise::V1::AnnotateAssessmentRequest
  sig do
    params(
      annotation: T.nilable(T.any(Symbol, Integer)),
      hashed_account_id: T.nilable(String),
      name: T.nilable(String),
      reasons: T.nilable(T.any(Google::Protobuf::RepeatedField[T.any(Symbol, Integer)], T::Array[T.any(Symbol, Integer)])),
      transaction_event: T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionEvent)
    ).void
  end
  def initialize(annotation: nil, hashed_account_id: nil, name: nil, reasons: Google::Protobuf::RepeatedField.new(:enum, T.any(Symbol, Integer)), transaction_event: nil); end

  sig { returns(T.any(Symbol, Integer)) }
  def annotation; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def annotation=(value); end

  sig { void }
  def clear_annotation; end

  sig { void }
  def clear_hashed_account_id; end

  sig { void }
  def clear_name; end

  sig { void }
  def clear_reasons; end

  sig { void }
  def clear_transaction_event; end

  sig { returns(String) }
  def hashed_account_id; end

  sig { params(value: String).void }
  def hashed_account_id=(value); end

  sig { returns(String) }
  def name; end

  sig { params(value: String).void }
  def name=(value); end

  sig { returns(Google::Protobuf::RepeatedField[T.any(Symbol, Integer)]) }
  def reasons; end

  sig { params(value: Google::Protobuf::RepeatedField[T.any(Symbol, Integer)]).void }
  def reasons=(value); end

  sig { returns(T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionEvent)) }
  def transaction_event; end

  sig { params(value: T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionEvent)).void }
  def transaction_event=(value); end
end
