# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Cloud::RecaptchaEnterprise::V1::ChallengeMetrics`.
# Please instead update this file by running `bin/tapioca dsl Google::Cloud::RecaptchaEnterprise::V1::ChallengeMetrics`.

class Google::Cloud::RecaptchaEnterprise::V1::ChallengeMetrics
  sig do
    params(
      failed_count: T.nilable(Integer),
      nocaptcha_count: T.nilable(Integer),
      pageload_count: T.nilable(Integer),
      passed_count: T.nilable(Integer)
    ).void
  end
  def initialize(failed_count: nil, nocaptcha_count: nil, pageload_count: nil, passed_count: nil); end

  sig { void }
  def clear_failed_count; end

  sig { void }
  def clear_nocaptcha_count; end

  sig { void }
  def clear_pageload_count; end

  sig { void }
  def clear_passed_count; end

  sig { returns(Integer) }
  def failed_count; end

  sig { params(value: Integer).void }
  def failed_count=(value); end

  sig { returns(Integer) }
  def nocaptcha_count; end

  sig { params(value: Integer).void }
  def nocaptcha_count=(value); end

  sig { returns(Integer) }
  def pageload_count; end

  sig { params(value: Integer).void }
  def pageload_count=(value); end

  sig { returns(Integer) }
  def passed_count; end

  sig { params(value: Integer).void }
  def passed_count=(value); end
end
