# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Cloud::RecaptchaEnterprise::V1::ListRelatedAccountGroupMembershipsRequest`.
# Please instead update this file by running `bin/tapioca dsl Google::Cloud::RecaptchaEnterprise::V1::ListRelatedAccountGroupMembershipsRequest`.

class Google::Cloud::RecaptchaEnterprise::V1::ListRelatedAccountGroupMembershipsRequest
  sig { params(page_size: T.nilable(Integer), page_token: T.nilable(String), parent: T.nilable(String)).void }
  def initialize(page_size: nil, page_token: nil, parent: nil); end

  sig { void }
  def clear_page_size; end

  sig { void }
  def clear_page_token; end

  sig { void }
  def clear_parent; end

  sig { returns(Integer) }
  def page_size; end

  sig { params(value: Integer).void }
  def page_size=(value); end

  sig { returns(String) }
  def page_token; end

  sig { params(value: String).void }
  def page_token=(value); end

  sig { returns(String) }
  def parent; end

  sig { params(value: String).void }
  def parent=(value); end
end
