# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Cloud::RecaptchaEnterprise::V1::Metrics`.
# Please instead update this file by running `bin/tapioca dsl Google::Cloud::RecaptchaEnterprise::V1::Metrics`.


class Google::Cloud::RecaptchaEnterprise::V1::Metrics < Google::Protobuf::AbstractMessage
  sig do
    params(
      challenge_metrics: T.nilable(T.any(Google::Protobuf::RepeatedField[Google::Cloud::RecaptchaEnterprise::V1::ChallengeMetrics], T::Array[Google::Cloud::RecaptchaEnterprise::V1::ChallengeMetrics])),
      name: T.nilable(String),
      score_metrics: T.nilable(T.any(Google::Protobuf::RepeatedField[Google::Cloud::RecaptchaEnterprise::V1::ScoreMetrics], T::Array[Google::Cloud::RecaptchaEnterprise::V1::ScoreMetrics])),
      start_time: T.nilable(Google::Protobuf::Timestamp)
    ).void
  end
  def initialize(challenge_metrics: T.unsafe(nil), name: nil, score_metrics: T.unsafe(nil), start_time: nil); end

  sig { returns(Google::Protobuf::RepeatedField[Google::Cloud::RecaptchaEnterprise::V1::ChallengeMetrics]) }
  def challenge_metrics; end

  sig { params(value: Google::Protobuf::RepeatedField[Google::Cloud::RecaptchaEnterprise::V1::ChallengeMetrics]).void }
  def challenge_metrics=(value); end

  sig { void }
  def clear_challenge_metrics; end

  sig { void }
  def clear_name; end

  sig { void }
  def clear_score_metrics; end

  sig { void }
  def clear_start_time; end

  sig { returns(Object) }
  def has_start_time?; end

  sig { returns(String) }
  def name; end

  sig { params(value: String).void }
  def name=(value); end

  sig { returns(Google::Protobuf::RepeatedField[Google::Cloud::RecaptchaEnterprise::V1::ScoreMetrics]) }
  def score_metrics; end

  sig { params(value: Google::Protobuf::RepeatedField[Google::Cloud::RecaptchaEnterprise::V1::ScoreMetrics]).void }
  def score_metrics=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def start_time; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def start_time=(value); end
end
