# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Cloud::RecaptchaEnterprise::V1::RiskAnalysis`.
# Please instead update this file by running `bin/tapioca dsl Google::Cloud::RecaptchaEnterprise::V1::RiskAnalysis`.

class Google::Cloud::RecaptchaEnterprise::V1::RiskAnalysis
  sig do
    params(
      reasons: T.nilable(T.any(Google::Protobuf::RepeatedField[T.any(Symbol, Integer)], T::Array[T.any(Symbol, Integer)])),
      score: T.nilable(Float)
    ).void
  end
  def initialize(reasons: Google::Protobuf::RepeatedField.new(:enum, T.any(Symbol, Integer)), score: nil); end

  sig { void }
  def clear_reasons; end

  sig { void }
  def clear_score; end

  sig { returns(Google::Protobuf::RepeatedField[T.any(Symbol, Integer)]) }
  def reasons; end

  sig { params(value: Google::Protobuf::RepeatedField[T.any(Symbol, Integer)]).void }
  def reasons=(value); end

  sig { returns(Float) }
  def score; end

  sig { params(value: Float).void }
  def score=(value); end
end
