# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Cloud::RecaptchaEnterprise::V1::TransactionData`.
# Please instead update this file by running `bin/tapioca dsl Google::Cloud::RecaptchaEnterprise::V1::TransactionData`.

class Google::Cloud::RecaptchaEnterprise::V1::TransactionData
  sig do
    params(
      billing_address: T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionData::Address),
      card_bin: T.nilable(String),
      card_last_four: T.nilable(String),
      currency_code: T.nilable(String),
      gateway_info: T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionData::GatewayInfo),
      items: T.nilable(T.any(Google::Protobuf::RepeatedField[Google::Cloud::RecaptchaEnterprise::V1::TransactionData::Item], T::Array[Google::Cloud::RecaptchaEnterprise::V1::TransactionData::Item])),
      merchants: T.nilable(T.any(Google::Protobuf::RepeatedField[Google::Cloud::RecaptchaEnterprise::V1::TransactionData::User], T::Array[Google::Cloud::RecaptchaEnterprise::V1::TransactionData::User])),
      payment_method: T.nilable(String),
      shipping_address: T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionData::Address),
      shipping_value: T.nilable(Float),
      transaction_id: T.nilable(String),
      user: T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionData::User),
      value: T.nilable(Float)
    ).void
  end
  def initialize(billing_address: nil, card_bin: nil, card_last_four: nil, currency_code: nil, gateway_info: nil, items: T.unsafe(nil), merchants: T.unsafe(nil), payment_method: nil, shipping_address: nil, shipping_value: nil, transaction_id: nil, user: nil, value: nil); end

  sig { returns(T.nilable(Symbol)) }
  def _transaction_id; end

  sig { returns(T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionData::Address)) }
  def billing_address; end

  sig { params(value: T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionData::Address)).void }
  def billing_address=(value); end

  sig { returns(String) }
  def card_bin; end

  sig { params(value: String).void }
  def card_bin=(value); end

  sig { returns(String) }
  def card_last_four; end

  sig { params(value: String).void }
  def card_last_four=(value); end

  sig { void }
  def clear_billing_address; end

  sig { void }
  def clear_card_bin; end

  sig { void }
  def clear_card_last_four; end

  sig { void }
  def clear_currency_code; end

  sig { void }
  def clear_gateway_info; end

  sig { void }
  def clear_items; end

  sig { void }
  def clear_merchants; end

  sig { void }
  def clear_payment_method; end

  sig { void }
  def clear_shipping_address; end

  sig { void }
  def clear_shipping_value; end

  sig { void }
  def clear_transaction_id; end

  sig { void }
  def clear_user; end

  sig { void }
  def clear_value; end

  sig { returns(String) }
  def currency_code; end

  sig { params(value: String).void }
  def currency_code=(value); end

  sig { returns(T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionData::GatewayInfo)) }
  def gateway_info; end

  sig { params(value: T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionData::GatewayInfo)).void }
  def gateway_info=(value); end

  sig { returns(Google::Protobuf::RepeatedField[Google::Cloud::RecaptchaEnterprise::V1::TransactionData::Item]) }
  def items; end

  sig do
    params(
      value: Google::Protobuf::RepeatedField[Google::Cloud::RecaptchaEnterprise::V1::TransactionData::Item]
    ).void
  end
  def items=(value); end

  sig { returns(Google::Protobuf::RepeatedField[Google::Cloud::RecaptchaEnterprise::V1::TransactionData::User]) }
  def merchants; end

  sig do
    params(
      value: Google::Protobuf::RepeatedField[Google::Cloud::RecaptchaEnterprise::V1::TransactionData::User]
    ).void
  end
  def merchants=(value); end

  sig { returns(String) }
  def payment_method; end

  sig { params(value: String).void }
  def payment_method=(value); end

  sig { returns(T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionData::Address)) }
  def shipping_address; end

  sig { params(value: T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionData::Address)).void }
  def shipping_address=(value); end

  sig { returns(Float) }
  def shipping_value; end

  sig { params(value: Float).void }
  def shipping_value=(value); end

  sig { returns(String) }
  def transaction_id; end

  sig { params(value: String).void }
  def transaction_id=(value); end

  sig { returns(T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionData::User)) }
  def user; end

  sig { params(value: T.nilable(Google::Cloud::RecaptchaEnterprise::V1::TransactionData::User)).void }
  def user=(value); end

  sig { returns(Float) }
  def value; end

  sig { params(value: Float).void }
  def value=(value); end
end
