# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ShopifyArea::ApplicationController`.
# Please instead update this file by running `bin/tapioca dsl ShopifyArea::ApplicationController`.


class ShopifyArea::ApplicationController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
