# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Doorkeeper::ApplicationsController`.
# Please instead update this file by running `bin/tapioca dsl Doorkeeper::ApplicationsController`.

class Doorkeeper::ApplicationsController
  sig { returns(HelperProxy) }
  def helpers; end

  module HelperMethods
    include ::Turbo::DriveHelper
    include ::Turbo::FramesHelper
    include ::Turbo::IncludesHelper
    include ::Turbo::StreamsHelper
    include ::Turbo::Streams::ActionHelper
    include ::ViteRails::TagHelpers
    include ::ActionController::Base::HelperMethods
    include ::Doorkeeper::DashboardHelper
  end

  class HelperProxy < ::ActionView::Base
    include HelperMethods
  end
end
