# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserEvent::Type::AutoUntagged`.
# Please instead update this file by running `bin/tapioca dsl UserEvent::Type::AutoUntagged`.


class UserEvent::Type::AutoUntagged
  include GeneratedAttributeMethods

  module GeneratedAttributeMethods
    sig { returns(T.nilable(::String)) }
    def auto_tagging_rule_id; end

    sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
    def auto_tagging_rule_id=(value); end

    sig { returns(T.nilable(::String)) }
    def tag_id; end

    sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
    def tag_id=(value); end
  end
end
