redis:
  url: <%= ENV['REDIS_URL'] %>
admin:
  auth0:
    auth0_domain: <%= ENV['ADMIN_AUTH0_DOMAIN'] %>
    auth0_client_id: <%= ENV['ADMIN_AUTH0_CLIENT_ID'] %>
    auth0_client_secret: <%= ENV['ADMIN_AUTH0_CLIENT_SECRET'] %>
ruler:
  auth0:
    auth0_domain: <%= ENV['RULER_AUTH0_DOMAIN'] %>
    auth0_client_id: <%= ENV['RULER_AUTH0_CLIENT_ID'] %>
    auth0_client_secret: <%= ENV['RULER_AUTH0_CLIENT_SECRET'] %>
blastengine:
  user_id: <%= ENV['BLASTENGINE_USER_ID'] %>
  api_key: <%= ENV['BLASTENGINE_API_KEY'] %>
account_lock:
  max_attempts: <%= ENV['ACCOUNT_LOCK_MAX_ATTEMPTS'] || 10 %>
  lockout_period_min: <%= ENV['LOCKOUT_PERIOD_MIN'] || 30 %>
aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] %>
  event_bus_name: <%= ENV['AWS_EVENT_BUS_NAME'] %>
doorkeeper:
  openid_connect:
    signing_key: <%= ENV['DOORKEEPER_OPENID_CONNECT_SIGNING_KEY'] %>
sms_link:
  api_token: <%= ENV['SMS_LINK_API_TOKEN'] %>
twilio:
  account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  api_key_sid: <%= ENV['TWILIO_API_KEY_SID'] %>
  api_key_secret: <%= ENV['TWILIO_API_KEY_SECRET'] %>
  sender_number: <%= ENV['TWILIO_SENDER_NUMBER'] %>
sms:
  disable_rate_limit: <%= ENV['SMS_DISABLE_RATE_LIMIT'] || false %>
domains:
  admin: <%= ENV['ADMIN_DOMAIN'] %>
  ruler: <%= ENV['RULER_DOMAIN'] %>
super_mode: <%= !!ActiveRecord::Type::Boolean.new.cast(ENV['SUPER_MODE']) %>
