development:
  :verbose: true
  :concurrency: 4
test:
  :verbose: true
  :concurrency: 4
staging:
  :concurrency: <%= (ENV['RAILS_MAX_THREADS'] || 5).to_i - 1 %>
production:
  :concurrency: <%= (ENV['RAILS_MAX_THREADS'] || 5).to_i - 1 %>
:queues: # queues are named by priority
  - [realtime_priority, 8]
  - [high_priority, 4]
  - [default, 2]
  - [low_priority, 1]
:scheduler:
  :schedule:
    expire_email_verifiers:
      cron: '0 0 0 1 * *'
      class: ExpireEmailVerifiersWorker
    delivery_setup:
      cron: '* * * * *'
      class: Deliveries::SetupWorker
      queue: default
      description: 'Setup scheduled deliveries for Blastengine bulk sending (~15 mins before)'
    confirm_import:
      cron: '* * * * *'
      class: Deliveries::ConfirmImportWorker
      queue: default
      description: 'Check CSV import status and commit deliveries when ready'
    confirm_result:
      cron: '*/15 * * * *'
      class: Deliveries::ConfirmResultWorker
      queue: low_priority
      description: 'Sync delivery results from Blastengine every 15 minutes (real-time sync on UI view)'
    birthday_setup:
      cron: '* * * * *'
      class: Deliveries::Birthday::SetupWorker
      queue: default
      description: 'Setup birthday deliveries for Blastengine bulk sending (~15 mins before)'
