# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Cloud::RecaptchaEnterprise::V1::TestingOptions::TestingChallenge`.
# Please instead update this file by running `bin/tapioca dsl Google::Cloud::RecaptchaEnterprise::V1::TestingOptions::TestingChallenge`.

module Google::Cloud::RecaptchaEnterprise::V1::TestingOptions::TestingChallenge
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Google::Cloud::RecaptchaEnterprise::V1::TestingOptions::TestingChallenge::NOCAPTCHA = 1
Google::Cloud::RecaptchaEnterprise::V1::TestingOptions::TestingChallenge::TESTING_CHALLENGE_UNSPECIFIED = 0
Google::Cloud::RecaptchaEnterprise::V1::TestingOptions::TestingChallenge::UNSOLVABLE_CHALLENGE = 2
