sms:
  disable_rate_limit: true
domains:
  admin: idp.localhost:3000
  ruler: localhost:3000
blastengine:
  rate_limit: 8
stripe:
  default_key_for_develop:
    name: 開発用キー
    publishable_key:
    secret_key:
    remote_id:
    tax_rate_id:
