admin:
  auth0:
    auth0_domain:
    auth0_client_id:
    auth0_client_secret:
ruler:
  auth0:
    auth0_domain:
    auth0_client_id:
    auth0_client_secret:
redis:
  url: <%= ENV['REDIS_URL'] %>
google_cloud_platform:
  recaptcha:
    project_id: this_id_project_id
    key: this_is_key
    google_cloud_service_account: |
      {}
