# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Cloud::RecaptchaEnterprise::V1::WafSettings::WafService`.
# Please instead update this file by running `bin/tapioca dsl Google::Cloud::RecaptchaEnterprise::V1::WafSettings::WafService`.


module Google::Cloud::RecaptchaEnterprise::V1::WafSettings::WafService
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Google::Cloud::RecaptchaEnterprise::V1::WafSettings::WafService::CA = 1
Google::Cloud::RecaptchaEnterprise::V1::WafSettings::WafService::FASTLY = 3
Google::Cloud::RecaptchaEnterprise::V1::WafSettings::WafService::WAF_SERVICE_UNSPECIFIED = 0
