# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Deliveries::ConfirmImportWorker`.
# Please instead update this file by running `bin/tapioca dsl Deliveries::ConfirmImportWorker`.


class Deliveries::ConfirmImportWorker
  class << self
    sig { params(type: T.untyped, record_id: T.untyped, tenant_id: T.untyped).returns(String) }
    def perform_async(type, record_id, tenant_id); end

    sig do
      params(
        interval: T.any(DateTime, Time, ActiveSupport::TimeWithZone),
        type: T.untyped,
        record_id: T.untyped,
        tenant_id: T.untyped
      ).returns(String)
    end
    def perform_at(interval, type, record_id, tenant_id); end

    sig do
      params(
        interval: T.any(Numeric, ActiveSupport::Duration),
        type: T.untyped,
        record_id: T.untyped,
        tenant_id: T.untyped
      ).returns(String)
    end
    def perform_in(interval, type, record_id, tenant_id); end
  end
end
